import { useState } from 'react';
import { Link } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import ReactMarkdown from 'react-markdown';
import { FileText, Download, Loader2, Lock, Check } from 'lucide-react';

// AI Bid Writer — the first original Toolio product ($29).
// Construction contractors input project details and get a professional,
// client-ready bid proposal generated by AI. Free preview; full export
// requires purchase via the Toolio store checkout.

const TRADES = ['General', 'Concrete & Flooring', 'Electrical', 'Plumbing', 'HVAC', 'Roofing', 'Framing', 'Drywall & Painting', 'Epoxy & Coatings', 'Excavation', 'Remodeling', 'Other'];

export default function AiBidWriter() {
  const [form, setForm] = useState({
    project_name: '', project_type: 'General Construction', scope_of_work: '',
    location: '', timeline: '', materials_cost: '', labor_hours: '', labor_rate: 65,
    overhead_pct: 15, profit_pct: 20, contractor_name: '', contractor_license: '',
    contractor_phone: '', contractor_email: '', client_name: '', client_company: ''
  });
  const [bid, setBid] = useState(null);
  const [pricing, setPricing] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [unlocked, setUnlocked] = useState(false);

  const set = (k, v) => setForm(f => ({ ...f, [k]: v }));

  async function generateBid() {
    if (!form.project_name || !form.scope_of_work) {
      setError('Project name and scope of work are required.');
      return;
    }
    setLoading(true); setError(''); setBid(null); setPricing(null);
    try {
      const res = await base44.functions.invoke('generateBidProposal', form);
      const data = res.data || res;
      if (data.error) throw new Error(data.error);
      setBid(data.bid_markdown);
      setPricing(data.pricing);
    } catch (e) {
      setError(e.message || 'Failed to generate bid.');
    } finally {
      setLoading(false);
    }
  }

  function downloadBid() {
    if (!bid) return;
    const blob = new Blob([bid], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${form.project_name.replace(/[^a-z0-9]/gi, '_')}_bid.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function startCheckout() {
    // Block checkout inside iframe (builder preview) — only works from published app
    if (window.self !== window.top) {
      alert('Checkout works only from the published app. Open this page in a new tab to purchase.');
      return;
    }
    base44.functions.invoke('toolioCheckout', {
      product_id: 'ai-tools',
      price: 29,
      success_url: window.location.href + '?unlocked=true',
      cancel_url: window.location.href
    }).then(res => {
      const data = res.data || res;
      if (data.url) window.location.href = data.url;
    }).catch(e => setError('Checkout failed: ' + e.message));
  }

  // Check for unlocked flag from checkout redirect
  if (typeof window !== 'undefined' && window.location.search.includes('unlocked=true') && !unlocked) {
    setUnlocked(true);
  }

  const previewOnly = bid && !unlocked;

  return (
    <div className="min-h-screen bg-[#f7f7f5]">
      {/* Header */}
      <header className="bg-[#0a0a0a] text-white px-6 py-4 sticky top-0 z-40 border-b border-[#2b2b2b]">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <Link to="/store" className="flex items-center gap-2 text-sm font-semibold text-[#E7C86E]">
            ← Toolio Store
          </Link>
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-[#E7C86E]" />
            <span className="font-bold">AI Bid Writer</span>
            <span className="text-xs bg-[#C89B3C] text-black px-2 py-0.5 rounded-full font-bold ml-2">$29</span>
          </div>
        </div>
      </header>

      <div className="max-w-6xl mx-auto px-6 py-8">
        {/* Hero */}
        <div className="text-center mb-8">
          <p className="text-[#C89B3C] text-xs font-bold uppercase tracking-widest mb-2">Construction AI Tool</p>
          <h1 className="font-display text-4xl md:text-5xl mb-3" style={{ fontFamily: "'Libre Caslon Display', serif" }}>
            AI Bid Writer
          </h1>
          <p className="text-gray-600 max-w-2xl mx-auto">
            Generate professional, client-ready construction bid proposals in seconds.
            Input your project details and get a complete bid with cover letter, scope of work,
            pricing breakdown, timeline, and terms — ready to send.
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-6">
          {/* Form */}
          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h2 className="font-bold text-lg mb-4 flex items-center gap-2">
              <span className="w-6 h-6 rounded-full bg-[#0a0a0a] text-white text-xs flex items-center justify-center">1</span>
              Project Details
            </h2>
            <div className="space-y-3">
              <div className="grid grid-cols-2 gap-3">
                <Field label="Project Name *">
                  <input value={form.project_name} onChange={e => set('project_name', e.target.value)} placeholder="Kitchen Remodel" className="fl-input" />
                </Field>
                <Field label="Project Type">
                  <select value={form.project_type} onChange={e => set('project_type', e.target.value)} className="fl-input">
                    {TRADES.map(t => <option key={t}>{t}</option>)}
                  </select>
                </Field>
              </div>
              <Field label="Scope of Work *">
                <textarea value={form.scope_of_work} onChange={e => set('scope_of_work', e.target.value)} rows={4} placeholder="Describe the work: demolition of existing kitchen, install new cabinets, countertops, flooring, plumbing fixtures, electrical, paint..." className="fl-input" />
              </Field>
              <div className="grid grid-cols-2 gap-3">
                <Field label="Location">
                  <input value={form.location} onChange={e => set('location', e.target.value)} placeholder="123 Main St, Austin TX" className="fl-input" />
                </Field>
                <Field label="Timeline">
                  <input value={form.timeline} onChange={e => set('timeline', e.target.value)} placeholder="4 weeks" className="fl-input" />
                </Field>
              </div>

              <h3 className="font-bold text-sm pt-3 border-t border-gray-100 mt-4">Pricing Inputs</h3>
              <div className="grid grid-cols-3 gap-3">
                <Field label="Materials Cost ($)">
                  <input type="number" value={form.materials_cost} onChange={e => set('materials_cost', e.target.value)} placeholder="5000" className="fl-input" />
                </Field>
                <Field label="Labor Hours">
                  <input type="number" value={form.labor_hours} onChange={e => set('labor_hours', e.target.value)} placeholder="80" className="fl-input" />
                </Field>
                <Field label="Labor Rate ($/hr)">
                  <input type="number" value={form.labor_rate} onChange={e => set('labor_rate', e.target.value)} className="fl-input" />
                </Field>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <Field label="Overhead (%)">
                  <input type="number" value={form.overhead_pct} onChange={e => set('overhead_pct', e.target.value)} className="fl-input" />
                </Field>
                <Field label="Profit Margin (%)">
                  <input type="number" value={form.profit_pct} onChange={e => set('profit_pct', e.target.value)} className="fl-input" />
                </Field>
              </div>

              <h3 className="font-bold text-sm pt-3 border-t border-gray-100 mt-4">Contractor Info</h3>
              <div className="grid grid-cols-2 gap-3">
                <Field label="Company Name">
                  <input value={form.contractor_name} onChange={e => set('contractor_name', e.target.value)} placeholder="ABC Construction LLC" className="fl-input" />
                </Field>
                <Field label="License #">
                  <input value={form.contractor_license} onChange={e => set('contractor_license', e.target.value)} placeholder="TX-12345" className="fl-input" />
                </Field>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <Field label="Phone">
                  <input value={form.contractor_phone} onChange={e => set('contractor_phone', e.target.value)} placeholder="(512) 555-0100" className="fl-input" />
                </Field>
                <Field label="Email">
                  <input value={form.contractor_email} onChange={e => set('contractor_email', e.target.value)} placeholder="bid@abcconstruction.com" className="fl-input" />
                </Field>
              </div>

              <h3 className="font-bold text-sm pt-3 border-t border-gray-100 mt-4">Client Info</h3>
              <div className="grid grid-cols-2 gap-3">
                <Field label="Client Name">
                  <input value={form.client_name} onChange={e => set('client_name', e.target.value)} placeholder="John Smith" className="fl-input" />
                </Field>
                <Field label="Client Company">
                  <input value={form.client_company} onChange={e => set('client_company', e.target.value)} placeholder="Smith Properties" className="fl-input" />
                </Field>
              </div>

              <button
                onClick={generateBid}
                disabled={loading}
                className="w-full bg-[#0a0a0a] text-white font-bold py-3 rounded-lg hover:bg-[#222] disabled:opacity-50 flex items-center justify-center gap-2 mt-2"
              >
                {loading ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating Bid…</> : <><FileText className="w-4 h-4" /> Generate Bid Proposal</>}
              </button>
              {error && <p className="text-red-600 text-sm">{error}</p>}
            </div>
          </div>

          {/* Output */}
          <div className="bg-white border border-gray-200 rounded-xl p-6 lg:sticky lg:top-24 lg:max-h-[calc(100vh-7rem)] lg:overflow-y-auto">
            <div className="flex items-center justify-between mb-4">
              <h2 className="font-bold text-lg flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-[#C89B3C] text-black text-xs flex items-center justify-center">2</span>
                Generated Bid
              </h2>
              {bid && unlocked && (
                <button onClick={downloadBid} className="flex items-center gap-1 text-sm font-semibold text-[#C89B3C] hover:underline">
                  <Download className="w-4 h-4" /> Download
                </button>
              )}
            </div>

            {/* Pricing summary */}
            {pricing && (
              <div className="bg-[#f7f7f5] border border-gray-200 rounded-lg p-4 mb-4">
                <div className="grid grid-cols-2 gap-y-1 text-sm">
                  <span className="text-gray-600">Materials:</span><span className="text-right font-semibold">${pricing.materials.toLocaleString()}</span>
                  <span className="text-gray-600">Labor ({pricing.labor_hours}h @ ${pricing.labor_rate}):</span><span className="text-right font-semibold">${pricing.labor_total.toLocaleString()}</span>
                  <span className="text-gray-600">Subtotal:</span><span className="text-right font-semibold">${pricing.subtotal.toLocaleString()}</span>
                  <span className="text-gray-600">Overhead ({pricing.overhead_pct}%):</span><span className="text-right font-semibold">${pricing.overhead_total.toLocaleString()}</span>
                  <span className="text-gray-600">Profit ({pricing.profit_pct}%):</span><span className="text-right font-semibold">${pricing.profit_total.toLocaleString()}</span>
                  <span className="text-gray-900 font-bold pt-2 border-t border-gray-300 mt-1">TOTAL BID:</span>
                  <span className="text-right font-bold text-lg text-[#0a0a0a] pt-2 border-t border-gray-300 mt-1">${pricing.total.toLocaleString()}</span>
                </div>
              </div>
            )}

            {/* Bid document */}
            {!bid && !loading && (
              <div className="text-center py-16 text-gray-400">
                <FileText className="w-12 h-12 mx-auto mb-3 opacity-30" />
                <p className="text-sm">Fill in the project details and click "Generate Bid" to create a professional, client-ready proposal.</p>
              </div>
            )}

            {bid && (
              <>
                <div className={previewOnly ? 'relative' : ''}>
                  <div className={previewOnly ? 'max-h-72 overflow-hidden' : ''}>
                    <div className="prose prose-sm max-w-none">
                      <ReactMarkdown>{bid}</ReactMarkdown>
                    </div>
                  </div>
                  {previewOnly && (
                    <div className="absolute inset-x-0 bottom-0 h-32 bg-gradient-to-t from-white to-transparent flex flex-col items-center justify-end pb-2">
                      <div className="text-center">
                        <Lock className="w-5 h-5 mx-auto mb-1 text-[#C89B3C]" />
                        <p className="text-xs text-gray-600 mb-2">Full bid locked. Purchase to unlock & download.</p>
                      </div>
                    </div>
                  )}
                </div>

                {previewOnly && (
                  <div className="mt-4 bg-[#0a0a0a] text-white rounded-lg p-5 text-center">
                    <p className="text-sm mb-3">Unlock the full bid proposal + download as markdown</p>
                    <button onClick={startCheckout} className="bg-[#C89B3C] text-black font-bold px-6 py-2.5 rounded-lg hover:bg-[#E7C86E] inline-flex items-center gap-2">
                      <Lock className="w-4 h-4" /> Unlock for $29
                    </button>
                    <p className="text-xs text-gray-400 mt-2">Lifetime access · Instant unlock · Secure checkout</p>
                  </div>
                )}

                {unlocked && (
                  <div className="mt-4 bg-green-50 border border-green-200 rounded-lg p-3 flex items-center gap-2 text-sm text-green-800">
                    <Check className="w-4 h-4" /> Full bid unlocked — download and send to your client.
                  </div>
                )}
              </>
            )}
          </div>
        </div>

        {/* Features */}
        <div className="mt-12 grid md:grid-cols-3 gap-4">
          {[
            ['Professional Cover Letter', 'AI-written intro that positions you as the expert.'],
            ['Detailed Scope of Work', 'Phased breakdown with specific tasks for each trade.'],
            ['Accurate Pricing', 'Deterministic math — materials, labor, overhead, and profit calculated precisely.'],
            ['Timeline & Milestones', 'Phased schedule with durations your client can follow.'],
            ['Terms & Conditions', 'Standard payment schedule, warranty, and change order policy included.'],
            ['Signature Block', 'Ready for both you and your client to sign and date.']
          ].map(([title, desc]) => (
            <div key={title} className="bg-white border border-gray-200 rounded-lg p-4">
              <h3 className="font-bold text-sm mb-1">{title}</h3>
              <p className="text-xs text-gray-600">{desc}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function Field({ label, children }) {
  return (
    <label className="block">
      <span className="text-xs font-semibold text-gray-700 mb-1 block">{label}</span>
      {children}
    </label>
  );
}