import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';

// End-to-end project launcher: creates a Google Drive folder, GitHub repo,
// Supabase project, Vercel project + deployment, and optionally purchases a
// domain through Vercel's registrar — all in one orchestrated call.
// Each step runs independently and collects its own errors so partial success
// is always reported back.

async function sha256hex(data) {
  const buf = await crypto.subtle.digest('SHA-256', data);
  return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, '0')).join('');
}

async function createDriveFolder(token, name) {
  const res = await fetch('https://www.googleapis.com/drive/v3/files', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name, mimeType: 'application/vnd.google-apps.folder' })
  });
  if (!res.ok) throw new Error(`Drive folder failed (${res.status}): ${await res.text()}`);
  const d = await res.json();
  return { id: d.id, url: `https://drive.google.com/drive/folders/${d.id}` };
}

async function createGitHubRepo(token, name) {
  const res = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', Accept: 'application/vnd.github+json' },
    body: JSON.stringify({ name, private: true, auto_init: true, description: 'Generated by FaultLine AI' })
  });
  if (!res.ok) throw new Error(`GitHub repo failed (${res.status}): ${await res.text()}`);
  const d = await res.json();
  return { id: d.id, name: d.full_name, url: d.html_url, owner: d.owner.login, default_branch: d.default_branch };
}

async function pushGitHubFile(token, owner, repo, path, content, message) {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
    method: 'PUT',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', Accept: 'application/vnd.github+json' },
    body: JSON.stringify({ message, content: btoa(unescape(encodeURIComponent(content))) })
  });
  if (!res.ok) throw new Error(`GitHub push failed (${res.status}): ${await res.text()}`);
  return await res.json();
}

async function createSupabaseProject(token, name) {
  const dbPass = crypto.randomUUID().replace(/-/g, '').slice(0, 24) + 'A1!';
  const res = await fetch('https://api.supabase.com/v1/projects', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name, db_pass: dbPass, region: 'us-east-1', plan: 'free' })
  });
  if (!res.ok) throw new Error(`Supabase project failed (${res.status}): ${await res.text()}`);
  const d = await res.json();
  return { id: d.id, ref: d.ref, url: `https://supabase.com/dashboard/project/${d.ref}`, db_password: dbPass, status: d.status };
}

async function createVercelProject(token, teamId, name) {
  const url = `https://api.vercel.com/v10/projects${teamId ? `?teamId=${teamId}` : ''}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name })
  });
  if (!res.ok) throw new Error(`Vercel project failed (${res.status}): ${await res.text()}`);
  const d = await res.json();
  return { id: d.id, name: d.name };
}

async function deployToVercel(token, teamId, projectName, html) {
  const fileData = new TextEncoder().encode(html);
  const sha = await sha256hex(fileData);
  const uploadUrl = `https://api.vercel.com/v2/files${teamId ? `?teamId=${teamId}` : ''}`;
  const upRes = await fetch(uploadUrl, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/octet-stream', 'x-vercel-digest': sha },
    body: fileData
  });
  if (!upRes.ok) throw new Error(`Vercel file upload failed (${upRes.status}): ${await upRes.text()}`);
  const depUrl = `https://api.vercel.com/v13/deployments${teamId ? `?teamId=${teamId}` : ''}`;
  const depRes = await fetch(depUrl, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name: projectName, files: [{ file: 'index.html', sha }], target: 'production', projectSettings: { framework: null } })
  });
  if (!depRes.ok) throw new Error(`Vercel deploy failed (${depRes.status}): ${await depRes.text()}`);
  const d = await depRes.json();
  return { id: d.id, url: d.url ? `https://${d.url}` : null, readyState: d.readyState, alias: d.alias || [] };
}

async function buyDomain(token, teamId, domain, contactInfo) {
  const url = `https://api.vercel.com/v1/registrar/domains/${domain}/buy${teamId ? `?teamId=${teamId}` : ''}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ autoRenew: true, years: 1, expectedPrice: 0, contactInformation: contactInfo })
  });
  if (!res.ok) throw new Error(`Domain purchase failed (${res.status}): ${await res.text()}`);
  return await res.json();
}

async function addDomainToProject(token, teamId, projectId, domain) {
  const url = `https://api.vercel.com/v9/projects/${projectId}/domains${teamId ? `?teamId=${teamId}` : ''}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name: domain })
  });
  if (!res.ok) throw new Error(`Attach domain failed (${res.status}): ${await res.text()}`);
  return await res.json();
}

export default async function(req) {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
    const orgId = user.data?.organization_id;

    const body = await req.json().catch(() => ({}));
    const { project_name, website_html, domain_name, steps, contact_info } = body;
    if (!project_name) return Response.json({ error: 'project_name required' }, { status: 400 });

    const want = steps || { drive: true, github: true, supabase: true, vercel: true, domain: false };
    const results = {};
    const errors = [];
    const slug = project_name.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '').slice(0, 40) || 'faultline-site';
    const html = website_html || '<!DOCTYPE html><html><head><title>Site</title></head><body><h1>Coming Soon</h1></body></html>';

    // 1. Google Drive folder (uses authorized connector)
    if (want.drive) {
      try {
        const conn = await base44.asServiceRole.connectors.getConnection('googledrive');
        results.drive = await createDriveFolder(conn.access_token, `${project_name} Website Assets`);
      } catch (e) { errors.push({ step: 'drive', error: e.message }); }
    }

    // 2. GitHub repo + push website
    if (want.github) {
      try {
        const token = Deno.env.get('GITHUB_TOKEN');
        if (!token) throw new Error('GITHUB_TOKEN secret not set');
        const repo = await createGitHubRepo(token, slug);
        await pushGitHubFile(token, repo.owner, slug, 'index.html', html, 'Initial website from FaultLine AI');
        results.github = repo;
      } catch (e) { errors.push({ step: 'github', error: e.message }); }
    }

    // 3. Supabase project
    if (want.supabase) {
      try {
        const token = Deno.env.get('SUPABASE_ACCESS_TOKEN');
        if (!token) throw new Error('SUPABASE_ACCESS_TOKEN secret not set');
        results.supabase = await createSupabaseProject(token, slug);
      } catch (e) { errors.push({ step: 'supabase', error: e.message }); }
    }

    // 4. Vercel project + deploy
    if (want.vercel) {
      try {
        const token = Deno.env.get('VERCEL_TOKEN');
        if (!token) throw new Error('VERCEL_TOKEN secret not set');
        const teamId = Deno.env.get('VERCEL_TEAM_ID') || null;
        const project = await createVercelProject(token, teamId, slug);
        const deploy = await deployToVercel(token, teamId, slug, html);
        results.vercel = { project, deploy };
      } catch (e) { errors.push({ step: 'vercel', error: e.message }); }
    }

    // 5. Domain purchase via Vercel registrar + attach to project
    if (want.domain && domain_name) {
      try {
        const token = Deno.env.get('VERCEL_TOKEN');
        if (!token) throw new Error('VERCEL_TOKEN secret not set');
        const teamId = Deno.env.get('VERCEL_TEAM_ID') || null;
        const order = await buyDomain(token, teamId, domain_name, contact_info || {});
        results.domain = { purchased: true, name: domain_name, order };
        if (results.vercel?.project?.id) {
          try {
            await addDomainToProject(token, teamId, results.vercel.project.id, domain_name);
            results.domain.attached = true;
          } catch (e) { errors.push({ step: 'domain_attach', error: e.message }); }
        }
      } catch (e) { errors.push({ step: 'domain', error: e.message }); }
    }

    await base44.asServiceRole.entities.Receipt.create({
      organization_id: orgId,
      system: 'project_launcher',
      action: 'launch',
      status: errors.length === 0 ? 'success' : 'partial',
      summary: `Launched ${project_name}: ${Object.keys(results).join(', ') || 'none'}`,
      evidence: { results, errors: errors.length ? errors : undefined }
    });

    return Response.json({
      status: errors.length === 0 ? 'success' : 'partial',
      project_name,
      slug,
      results,
      errors: errors.length ? errors : undefined
    });
  } catch (error) {
    console.error('launchProject error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
}