// Shared infrastructure provisioning helpers — Google Drive folder, GitHub repo,
// Supabase project, Vercel project + deployment. Used by the autonomous launch
// pipeline so each step is isolated and independently testable.

export async function sha1hex(data) {
  const buf = await crypto.subtle.digest('SHA-1', data);
  return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, '0')).join('');
}

export function slugify(name) {
  return (name || '').toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '').slice(0, 40) || 'faultline-site';
}

export async function createDriveFolder(token, name) {
  const res = await fetch('https://www.googleapis.com/drive/v3/files', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name, mimeType: 'application/vnd.google-apps.folder' })
  });
  if (!res.ok) throw new Error(`Drive folder failed (${res.status}): ${(await res.text()).slice(0, 200)}`);
  const d = await res.json();
  return { id: d.id, url: `https://drive.google.com/drive/folders/${d.id}` };
}

export async function createGitHubRepo(token, name) {
  const res = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', Accept: 'application/vnd.github+json', 'User-Agent': 'FaultLine-AI-Launch-Pipeline', 'X-GitHub-Api-Version': '2022-11-28' },
    body: JSON.stringify({ name, private: true, auto_init: true, description: 'Generated by FaultLine AI Autonomous Launch Pipeline' })
  });
  if (!res.ok) throw new Error(`GitHub repo failed (${res.status}): ${(await res.text()).slice(0, 200)}`);
  const d = await res.json();
  return { id: d.id, name: d.full_name, url: d.html_url, owner: d.owner.login, default_branch: d.default_branch };
}

export async function pushGitHubFile(token, owner, repo, path, content, message) {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
    method: 'PUT',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', Accept: 'application/vnd.github+json', 'User-Agent': 'FaultLine-AI-Launch-Pipeline', 'X-GitHub-Api-Version': '2022-11-28' },
    body: JSON.stringify({ message, content: btoa(unescape(encodeURIComponent(content))) })
  });
  if (!res.ok) throw new Error(`GitHub push failed (${res.status}): ${(await res.text()).slice(0, 200)}`);
  return await res.json();
}

export async function createSupabaseProject(token, name) {
  const dbPass = crypto.randomUUID().replace(/-/g, '').slice(0, 24) + 'A1!';
  const res = await fetch('https://api.supabase.com/v1/projects', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name, db_pass: dbPass, region: 'us-east-1', plan: 'free' })
  });
  if (!res.ok) throw new Error(`Supabase project failed (${res.status}): ${(await res.text()).slice(0, 200)}`);
  const d = await res.json();
  return { id: d.id, ref: d.ref, url: `https://supabase.com/dashboard/project/${d.ref}`, db_password: dbPass, status: d.status };
}

export async function createVercelProject(token, teamId, name) {
  const url = `https://api.vercel.com/v10/projects${teamId ? `?teamId=${teamId}` : ''}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name })
  });
  if (!res.ok) throw new Error(`Vercel project failed (${res.status}): ${(await res.text()).slice(0, 200)}`);
  const d = await res.json();
  return { id: d.id, name: d.name };
}

export async function disableVercelSso(token, teamId, projectId) {
  const url = `https://api.vercel.com/v9/projects/${projectId}${teamId ? `?teamId=${teamId}` : ''}`;
  const res = await fetch(url, {
    method: 'PATCH',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ ssoProtection: null })
  });
  if (!res.ok) throw new Error(`Vercel SSO disable failed (${res.status}): ${(await res.text()).slice(0, 200)}`);
  return true;
}

export async function deployToVercel(token, teamId, projectName, projectId, html) {
  const fileData = new TextEncoder().encode(html);
  const sha = await sha1hex(fileData);
  const size = fileData.length;
  const uploadUrl = `https://api.vercel.com/v2/files${teamId ? `?teamId=${teamId}` : ''}`;
  const upRes = await fetch(uploadUrl, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/octet-stream', 'x-vercel-digest': sha },
    body: fileData
  });
  if (!upRes.ok) throw new Error(`Vercel file upload failed (${upRes.status}): ${(await upRes.text()).slice(0, 200)}`);
  const depUrl = `https://api.vercel.com/v13/deployments${teamId ? `?teamId=${teamId}` : ''}`;
  const depBody = { name: projectName, files: [{ file: 'index.html', sha, size }], target: 'production', projectSettings: { framework: null } };
  if (projectId) depBody.project = projectId;
  const depRes = await fetch(depUrl, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify(depBody)
  });
  if (!depRes.ok) throw new Error(`Vercel deploy failed (${depRes.status}): ${(await depRes.text()).slice(0, 200)}`);
  const d = await depRes.json();
  return { id: d.id, url: d.url ? `https://${d.url}` : null, readyState: d.readyState, alias: d.alias || [] };
}