// Shared infrastructure provisioning helpers — Google Drive folder, GitHub repo,
// Supabase project, Vercel project + deployment. Used by the autonomous launch
// pipeline so each step is isolated and independently testable.

export async function sha1hex(data) {
  const buf = await crypto.subtle.digest('SHA-1', data);
  return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, '0')).join('');
}

export function slugify(name) {
  return (name || '').toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '').slice(0, 40) || 'faultline-site';
}

export async function createDriveFolder(token, name) {
  const res = await fetch('https://www.googleapis.com/drive/v3/files', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name, mimeType: 'application/vnd.google-apps.folder' })
  });
  if (!res.ok) throw new Error(`Drive folder failed (${res.status}): ${(await res.text()).slice(0, 200)}`);
  const d = await res.json();
  return { id: d.id, url: `https://drive.google.com/drive/folders/${d.id}` };
}

export async function createGitHubRepo(token, name) {
  const res = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', Accept: 'application/vnd.github+json', 'User-Agent': 'FaultLine-AI-Launch-Pipeline', 'X-GitHub-Api-Version': '2022-11-28' },
    body: JSON.stringify({ name, private: true, auto_init: true, description: 'Generated by FaultLine AI Autonomous Launch Pipeline' })
  });
  if (!res.ok) {
    const errText = await res.text();
    // Name collision — reuse existing repo instead of failing
    if (res.status === 422 && /already exists/i.test(errText)) {
      const userRes = await fetch('https://api.github.com/user', { headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json', 'User-Agent': 'FaultLine-AI-Launch-Pipeline' } });
      if (userRes.ok) {
        const user = await userRes.json();
        const repoRes = await fetch(`https://api.github.com/repos/${user.login}/${name}`, { headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json', 'User-Agent': 'FaultLine-AI-Launch-Pipeline' } });
        if (repoRes.ok) {
          const d = await repoRes.json();
          return { id: d.id, name: d.full_name, url: d.html_url, owner: d.owner.login, default_branch: d.default_branch, reused: true };
        }
      }
    }
    throw new Error(`GitHub repo failed (${res.status}): ${errText.slice(0, 200)}`);
  }
  const d = await res.json();
  return { id: d.id, name: d.full_name, url: d.html_url, owner: d.owner.login, default_branch: d.default_branch };
}

export async function pushGitHubFile(token, owner, repo, path, content, message) {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
    method: 'PUT',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', Accept: 'application/vnd.github+json', 'User-Agent': 'FaultLine-AI-Launch-Pipeline', 'X-GitHub-Api-Version': '2022-11-28' },
    body: JSON.stringify({ message, content: btoa(unescape(encodeURIComponent(content))) })
  });
  if (!res.ok) throw new Error(`GitHub push failed (${res.status}): ${(await res.text()).slice(0, 200)}`);
  return await res.json();
}

export async function createSupabaseProject(token, name) {
  const dbPass = crypto.randomUUID().replace(/-/g, '').slice(0, 24) + 'A1!';
  // Supabase requires an organization context — list orgs and use the first one
  const orgRes = await fetch('https://api.supabase.com/v1/organizations', {
    headers: { Authorization: `Bearer ${token}` }
  });
  let orgId = null;
  if (orgRes.ok) {
    const orgs = await orgRes.json();
    if (Array.isArray(orgs) && orgs.length > 0) orgId = orgs[0].id;
  }
  const res = await fetch('https://api.supabase.com/v1/projects', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name, db_pass: dbPass, region: 'us-east-1', plan: 'free', ...(orgId ? { organization_id: orgId } : {}) })
  });
  if (!res.ok) {
    const raw = await res.text();
    let msg = raw;
    try { const j = JSON.parse(raw); msg = j.message || j.error || raw; } catch (e) {}
    // Name collision — reuse existing project instead of failing
    if (/already exists/i.test(msg)) {
      const listRes = await fetch('https://api.supabase.com/v1/projects', { headers: { Authorization: `Bearer ${token}` } });
      if (listRes.ok) {
        const projects = await listRes.json();
        const existing = (Array.isArray(projects) ? projects : []).find(p => p.name === name);
        if (existing) return { id: existing.id, ref: existing.ref, url: `https://supabase.com/dashboard/project/${existing.ref}`, db_password: null, status: existing.status, reused: true };
      }
    }
    const limitHit = /limit|quota|free.?tier|exceeded/i.test(msg);
    throw new Error(limitHit
      ? `Supabase free-tier project limit reached — delete an unused project in the Supabase dashboard to free a slot. (${res.status})`
      : `Supabase project failed (${res.status}): ${String(msg).slice(0, 300)}`);
  }
  const d = await res.json();
  return { id: d.id, ref: d.ref, url: `https://supabase.com/dashboard/project/${d.ref}`, db_password: dbPass, status: d.status };
}

export async function createVercelProject(token, teamId, name) {
  const url = `https://api.vercel.com/v10/projects${teamId ? `?teamId=${teamId}` : ''}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name })
  });
  if (!res.ok) {
    const errText = await res.text();
    // Name collision — reuse existing project instead of failing
    if (res.status === 409 && /already exists/i.test(errText)) {
      const getRes = await fetch(`https://api.vercel.com/v9/projects/${name}${teamId ? `?teamId=${teamId}` : ''}`, { headers: { Authorization: `Bearer ${token}` } });
      if (getRes.ok) {
        const d = await getRes.json();
        return { id: d.id, name: d.name, reused: true };
      }
    }
    throw new Error(`Vercel project failed (${res.status}): ${errText.slice(0, 200)}`);
  }
  const d = await res.json();
  return { id: d.id, name: d.name };
}

export async function disableVercelSso(token, teamId, projectId) {
  const url = `https://api.vercel.com/v9/projects/${projectId}${teamId ? `?teamId=${teamId}` : ''}`;
  const res = await fetch(url, {
    method: 'PATCH',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ ssoProtection: null })
  });
  if (!res.ok) throw new Error(`Vercel SSO disable failed (${res.status}): ${(await res.text()).slice(0, 200)}`);
  return true;
}

export async function deployToVercel(token, teamId, projectName, projectId, html) {
  const fileData = new TextEncoder().encode(html);
  const sha = await sha1hex(fileData);
  const size = fileData.length;
  // Retry on 429 (rate limit) with exponential backoff: 2s, 4s, 8s
  const fetchWithRetry = async (url, opts, label) => {
    for (let attempt = 0; attempt < 3; attempt++) {
      const res = await fetch(url, opts);
      if (res.ok) return res;
      if (res.status === 429 && attempt < 2) {
        const wait = Math.pow(2, attempt + 1) * 1000;
        console.warn(`${label} got 429, retrying in ${wait / 1000}s (attempt ${attempt + 1}/3)`);
        await new Promise(r => setTimeout(r, wait));
        continue;
      }
      throw new Error(`${label} failed (${res.status}): ${(await res.text()).slice(0, 200)}`);
    }
  };
  const uploadUrl = `https://api.vercel.com/v2/files${teamId ? `?teamId=${teamId}` : ''}`;
  const upRes = await fetchWithRetry(uploadUrl, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/octet-stream', 'x-vercel-digest': sha },
    body: fileData
  }, 'Vercel file upload');
  const depUrl = `https://api.vercel.com/v13/deployments${teamId ? `?teamId=${teamId}` : ''}`;
  const depBody = { name: projectName, files: [{ file: 'index.html', sha, size }], target: 'production', projectSettings: { framework: null } };
  if (projectId) depBody.project = projectId;
  const depRes = await fetchWithRetry(depUrl, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify(depBody)
  }, 'Vercel deploy');
  const d = await depRes.json();
  return { id: d.id, url: d.url ? `https://${d.url}` : null, readyState: d.readyState, alias: d.alias || [] };
}