// Auto-generated from XTREME_AI_SYSTEMS_MASTER_CONTROL_WORKBOOK_V1.xlsx
// Source-truth registry data for the PCU/Xtreme Polishing System workflow

export const products = [
  {
    "tool_id": "TOOL-001",
    "name": "Premium Contractor Website",
    "category": "Brand & Website",
    "description": "Complete high-converting contractor website with services, locations, galleries, forms and portal connection.",
    "customer_outcome": "More qualified leads and trust",
    "best_for": "New PCU; Owner Operator; Growth",
    "setup_price": 1495,
    "monthly_price": 129,
    "revenue_model": "Managed",
    "release": "MVP",
    "core_entities": "WebsiteProject; WebsitePage",
    "dependencies": "Logo/brand, hosting, analytics",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-002",
    "name": "Logo and Brand System",
    "category": "Brand & Website",
    "description": "Three logo directions, brand packs, messaging and final asset kit.",
    "customer_outcome": "Look professional and memorable",
    "best_for": "New PCU; Rebrand",
    "setup_price": 795,
    "monthly_price": 49,
    "revenue_model": "Managed",
    "release": "MVP",
    "core_entities": "BrandPack; MediaAsset; Approval",
    "dependencies": "Image generation, storage",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-003",
    "name": "Website Conversion Upgrade",
    "category": "Brand & Website",
    "description": "Upgrade an existing website with stronger CTAs, lead forms, trust, speed and tracking.",
    "customer_outcome": "Convert more existing traffic",
    "best_for": "Established Contractor",
    "setup_price": 995,
    "monthly_price": 149,
    "revenue_model": "Managed",
    "release": "Growth",
    "core_entities": "WebsitePage; Event",
    "dependencies": "Analytics, forms",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-004",
    "name": "Local SEO Growth System",
    "category": "Lead Generation",
    "description": "Service and location content, GBP workflow, schema, internal linking and reporting.",
    "customer_outcome": "Generate local organic leads",
    "best_for": "Growth; Established",
    "setup_price": 995,
    "monthly_price": 299,
    "revenue_model": "Managed",
    "release": "Growth",
    "core_entities": "WebsitePage; MarketFinding; ReportSnapshot",
    "dependencies": "Search data, GBP",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-005",
    "name": "AI Receptionist",
    "category": "Communications",
    "description": "24/7 voice intake, qualification, booking, routing and summaries.",
    "customer_outcome": "Answer more opportunities",
    "best_for": "Owner Operator; Growth",
    "setup_price": 499,
    "monthly_price": 299,
    "revenue_model": "Usage + Subscription",
    "release": "Growth",
    "core_entities": "Call; Lead; Contact",
    "dependencies": "Twilio Voice, AI gateway",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-006",
    "name": "Missed-Call Text-Back",
    "category": "Communications",
    "description": "Immediate SMS response, intake link and follow-up when calls are missed.",
    "customer_outcome": "Recover lost leads",
    "best_for": "All contractors",
    "setup_price": 199,
    "monthly_price": 99,
    "revenue_model": "Usage + Subscription",
    "release": "MVP",
    "core_entities": "Call; Message; Lead",
    "dependencies": "Twilio SMS, consent",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-007",
    "name": "Unified SMS and Voice Inbox",
    "category": "Communications",
    "description": "Shared business number, texting, call history, templates and assignment.",
    "customer_outcome": "Keep customer communication organized",
    "best_for": "Growth; Multi-Crew",
    "setup_price": 299,
    "monthly_price": 149,
    "revenue_model": "Usage + Subscription",
    "release": "Growth",
    "core_entities": "Message; Channel; Call",
    "dependencies": "Twilio",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-008",
    "name": "WhatsApp Business Inbox",
    "category": "Communications",
    "description": "Customer conversations, templates and lead routing through WhatsApp.",
    "customer_outcome": "Reach customers in preferred channel",
    "best_for": "Selected markets",
    "setup_price": 299,
    "monthly_price": 99,
    "revenue_model": "Usage + Subscription",
    "release": "Growth",
    "core_entities": "Conversation; Contact; ConsentRecord",
    "dependencies": "Twilio/Meta approvals",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-009",
    "name": "Contractor CRM",
    "category": "Sales",
    "description": "Lead pipeline, tasks, activities, source attribution and customer history.",
    "customer_outcome": "Close more jobs with less leakage",
    "best_for": "Owner Operator; Growth",
    "setup_price": 499,
    "monthly_price": 149,
    "revenue_model": "Subscription",
    "release": "MVP",
    "core_entities": "Lead; Deal; Contact; Activity",
    "dependencies": "Forms, communications",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-010",
    "name": "AI Lead Qualifier",
    "category": "Sales",
    "description": "Asks project questions, scores fit and routes next actions.",
    "customer_outcome": "Focus on the best opportunities",
    "best_for": "Growth; Commercial",
    "setup_price": 299,
    "monthly_price": 99,
    "revenue_model": "Subscription",
    "release": "Growth",
    "core_entities": "Lead; ToolRecommendation",
    "dependencies": "Chat, forms",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-011",
    "name": "AI Estimator",
    "category": "Estimating",
    "description": "Guided measurements, substrate questions, pricing logic and preliminary ranges.",
    "customer_outcome": "Prepare estimates faster",
    "best_for": "All contractors",
    "setup_price": 995,
    "monthly_price": 199,
    "revenue_model": "Subscription",
    "release": "Growth",
    "core_entities": "PricingSetting; IntakeResponse",
    "dependencies": "Pricebook, approvals",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-012",
    "name": "Proposal Generator",
    "category": "Estimating",
    "description": "Professional proposal, scope, options, exclusions, terms and acceptance.",
    "customer_outcome": "Send better proposals faster",
    "best_for": "All contractors",
    "setup_price": 499,
    "monthly_price": 129,
    "revenue_model": "Subscription",
    "release": "Growth",
    "core_entities": "Proposal; VersionSnapshot",
    "dependencies": "E-sign, payments",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-013",
    "name": "Estimate Follow-Up Automation",
    "category": "Sales",
    "description": "Automated reminders, next-best action and dormant estimate nurture.",
    "customer_outcome": "Win more of the estimates already sent",
    "best_for": "All contractors",
    "setup_price": 299,
    "monthly_price": 129,
    "revenue_model": "Subscription",
    "release": "MVP",
    "core_entities": "Deal; Campaign; Message",
    "dependencies": "SMS/email consent",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-014",
    "name": "Floor Visualizer",
    "category": "Sales",
    "description": "Upload a space and preview selected floor finishes as disclosed concepts.",
    "customer_outcome": "Help buyers choose and convert",
    "best_for": "Residential; Decorative",
    "setup_price": 995,
    "monthly_price": 199,
    "revenue_model": "Usage + Subscription",
    "release": "Growth",
    "core_entities": "MediaGenerationJob; MediaAsset",
    "dependencies": "Image provider, storage",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-015",
    "name": "Review Automation",
    "category": "Reputation",
    "description": "Completion-triggered review requests, reminders and response drafts.",
    "customer_outcome": "Build trust and local visibility",
    "best_for": "All contractors",
    "setup_price": 199,
    "monthly_price": 99,
    "revenue_model": "Subscription",
    "release": "MVP",
    "core_entities": "Campaign; Contact; ConsentRecord",
    "dependencies": "SMS/email",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-016",
    "name": "Referral and Repeat Customer System",
    "category": "Retention",
    "description": "Referral requests, seasonal campaigns and dormant customer nurture.",
    "customer_outcome": "Lower acquisition cost",
    "best_for": "Established Contractor",
    "setup_price": 299,
    "monthly_price": 129,
    "revenue_model": "Subscription",
    "release": "Growth",
    "core_entities": "Campaign; Contact",
    "dependencies": "Messaging",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-017",
    "name": "AI Content Studio",
    "category": "Marketing",
    "description": "Project captions, blogs, emails, GBP posts, scripts and approval queues.",
    "customer_outcome": "Stay visible without constant writing",
    "best_for": "All contractors",
    "setup_price": 299,
    "monthly_price": 149,
    "revenue_model": "Subscription",
    "release": "Growth",
    "core_entities": "ContentAsset; Campaign",
    "dependencies": "Media, social adapters",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-018",
    "name": "Auto Social Publisher",
    "category": "Marketing",
    "description": "Scheduled approved content distribution and receipts.",
    "customer_outcome": "Publish consistently",
    "best_for": "Growth; Established",
    "setup_price": 399,
    "monthly_price": 199,
    "revenue_model": "Subscription",
    "release": "Advanced",
    "core_entities": "ContentAsset; Campaign; AuditLog",
    "dependencies": "Metricool/social APIs",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-019",
    "name": "Project Gallery Generator",
    "category": "Brand & Website",
    "description": "Transforms approved project photos into categorized galleries and case studies.",
    "customer_outcome": "Turn completed work into sales proof",
    "best_for": "All contractors",
    "setup_price": 299,
    "monthly_price": 79,
    "revenue_model": "Subscription",
    "release": "Growth",
    "core_entities": "MediaAsset; WebsitePage",
    "dependencies": "Storage, website",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-020",
    "name": "Commercial Project Discovery",
    "category": "Commercial",
    "description": "Finds relevant public and commercial projects and tracks evidence.",
    "customer_outcome": "Create a project pipeline",
    "best_for": "Commercial Contractor",
    "setup_price": 1495,
    "monthly_price": 499,
    "revenue_model": "Subscription",
    "release": "Advanced",
    "core_entities": "Opportunity; SourceRegistryV2",
    "dependencies": "Public/licensed sources",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-021",
    "name": "AI Takeoff Assistant",
    "category": "Commercial",
    "description": "Extracts flooring scopes and quantities from approved plans for human review.",
    "customer_outcome": "Reduce takeoff time",
    "best_for": "Commercial Contractor",
    "setup_price": 2500,
    "monthly_price": 799,
    "revenue_model": "Usage + Subscription",
    "release": "Advanced",
    "core_entities": "Takeoff; EvidenceArtifact",
    "dependencies": "Document AI, storage",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-022",
    "name": "Bid and Proposal Manager",
    "category": "Commercial",
    "description": "Bid calendar, addenda, compliance, proposal packages and GC follow-up.",
    "customer_outcome": "Submit more complete bids",
    "best_for": "Commercial Contractor",
    "setup_price": 1495,
    "monthly_price": 499,
    "revenue_model": "Subscription",
    "release": "Advanced",
    "core_entities": "Bid; ProposalPackage; ComplianceItem",
    "dependencies": "Drive, calendar",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-023",
    "name": "GC Relationship CRM",
    "category": "Commercial",
    "description": "Tracks general contractors, contacts, bidding status and award follow-up.",
    "customer_outcome": "Build stronger commercial relationships",
    "best_for": "Commercial Contractor",
    "setup_price": 799,
    "monthly_price": 299,
    "revenue_model": "Subscription",
    "release": "Advanced",
    "core_entities": "Company; Contact; CIBidderCoverage",
    "dependencies": "Research, communications",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-024",
    "name": "Job Startup Packet",
    "category": "Operations",
    "description": "Creates scope, contacts, schedule, materials, equipment, safety and customer plan.",
    "customer_outcome": "Start jobs organized",
    "best_for": "Growth; Commercial",
    "setup_price": 399,
    "monthly_price": 99,
    "revenue_model": "Subscription",
    "release": "Growth",
    "core_entities": "Project; WorkOrder; OperatingProcedure",
    "dependencies": "Calendar, storage",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-025",
    "name": "Crew Schedule and Dispatch",
    "category": "Operations",
    "description": "Crew assignments, project milestones, reminders and conflict detection.",
    "customer_outcome": "Reduce schedule chaos",
    "best_for": "Multi-Crew",
    "setup_price": 799,
    "monthly_price": 249,
    "revenue_model": "Subscription",
    "release": "Advanced",
    "core_entities": "ScheduleEvent; ProjectAssignment",
    "dependencies": "Calendar, maps",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-026",
    "name": "Field Photo and Daily Report",
    "category": "Operations",
    "description": "Mobile reports, required photo milestones, metadata and review.",
    "customer_outcome": "Document work and protect payments",
    "best_for": "Growth; Commercial",
    "setup_price": 499,
    "monthly_price": 149,
    "revenue_model": "Subscription",
    "release": "Growth",
    "core_entities": "FieldReport; PhotoEvidence",
    "dependencies": "Storage, mobile",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-027",
    "name": "Change Order System",
    "category": "Operations",
    "description": "Documents changed scope, cost, schedule and approval before work proceeds.",
    "customer_outcome": "Protect margin and reduce disputes",
    "best_for": "All contractors",
    "setup_price": 399,
    "monthly_price": 99,
    "revenue_model": "Subscription",
    "release": "Growth",
    "core_entities": "ChangeOrder; Approval",
    "dependencies": "E-sign, payments",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-028",
    "name": "Job Cost and Margin Dashboard",
    "category": "Finance",
    "description": "Estimated, committed and actual costs with variance and margin.",
    "customer_outcome": "Know which jobs make money",
    "best_for": "Growth; Established",
    "setup_price": 799,
    "monthly_price": 249,
    "revenue_model": "Subscription",
    "release": "Advanced",
    "core_entities": "JobCost; BillingRecord; ReportSnapshot",
    "dependencies": "Accounting adapters",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-029",
    "name": "Invoice and Collections Automation",
    "category": "Finance",
    "description": "Invoice triggers, reminders, hosted payment links and aging dashboard.",
    "customer_outcome": "Get paid faster",
    "best_for": "All contractors",
    "setup_price": 399,
    "monthly_price": 149,
    "revenue_model": "Subscription",
    "release": "Growth",
    "core_entities": "BillingRecord; Message",
    "dependencies": "Payments, accounting",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-030",
    "name": "Contractor Business Intelligence",
    "category": "Analytics",
    "description": "Leads, conversion, revenue, margin, marketing and product adoption.",
    "customer_outcome": "Run the company with clear numbers",
    "best_for": "Growth; Established",
    "setup_price": 799,
    "monthly_price": 249,
    "revenue_model": "Subscription",
    "release": "Advanced",
    "core_entities": "ReportSnapshot; Event",
    "dependencies": "Analytics warehouse",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-031",
    "name": "SOP and Training Assistant",
    "category": "Training",
    "description": "Searchable procedures, checklists, role training and quiz workflows.",
    "customer_outcome": "Train consistently",
    "best_for": "Multi-Crew",
    "setup_price": 499,
    "monthly_price": 149,
    "revenue_model": "Subscription",
    "release": "Advanced",
    "core_entities": "KnowledgeArticle; OperatingProcedure",
    "dependencies": "Knowledge base",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-032",
    "name": "Customer Support Assistant",
    "category": "Support",
    "description": "Answers approved product and account questions and creates escalations.",
    "customer_outcome": "Provide faster support",
    "best_for": "All customers",
    "setup_price": 199,
    "monthly_price": 79,
    "revenue_model": "Subscription",
    "release": "Growth",
    "core_entities": "SupportTicket; KnowledgeArticle",
    "dependencies": "Chat/email",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-033",
    "name": "Multi-Location Website Network",
    "category": "Brand & Website",
    "description": "Standardized location websites, lead routing and central analytics.",
    "customer_outcome": "Expand territories without brand drift",
    "best_for": "Regional Contractor",
    "setup_price": 5000,
    "monthly_price": 999,
    "revenue_model": "Managed + Subscription",
    "release": "Advanced",
    "core_entities": "WebsiteProject; Division; Lead",
    "dependencies": "Domains, analytics",
    "status": "DRAFT"
  },
  {
    "tool_id": "TOOL-034",
    "name": "Complete Contractor Operating System",
    "category": "Operating System",
    "description": "Connected website, CRM, communications, estimating, operations and analytics.",
    "customer_outcome": "Operate from one system",
    "best_for": "Growth; Established",
    "setup_price": 7500,
    "monthly_price": 999,
    "revenue_model": "Managed + Subscription",
    "release": "Advanced",
    "core_entities": "Core entities",
    "dependencies": "All approved integrations",
    "status": "DRAFT"
  }
];

export const packages = [
  {
    "package_id": "PKG-001",
    "name": "PCU Launch System",
    "audience": "New PCU students",
    "outcome": "Professional launch",
    "tool_ids": [
      "TOOL-001",
      "TOOL-002",
      "TOOL-006",
      "TOOL-015"
    ],
    "setup_price": 1495,
    "monthly_price": 149,
    "deliverables": "Website, logo, brand, lead form, missed-call recovery, review starter",
    "fulfillment_notes": "Managed onboarding",
    "status": "DRAFT"
  },
  {
    "package_id": "PKG-002",
    "name": "Lead Capture System",
    "audience": "Owner operators",
    "outcome": "Capture and respond to more leads",
    "tool_ids": [
      "TOOL-001",
      "TOOL-005",
      "TOOL-006",
      "TOOL-009",
      "TOOL-013"
    ],
    "setup_price": 2995,
    "monthly_price": 399,
    "deliverables": "Website, receptionist, SMS recovery, CRM, follow-up",
    "fulfillment_notes": "Usage allowance required",
    "status": "DRAFT"
  },
  {
    "package_id": "PKG-003",
    "name": "Contractor Growth System",
    "audience": "Small growth contractors",
    "outcome": "Close more jobs and reduce office work",
    "tool_ids": [
      "TOOL-003",
      "TOOL-007",
      "TOOL-009",
      "TOOL-011",
      "TOOL-012",
      "TOOL-013",
      "TOOL-015",
      "TOOL-017",
      "TOOL-030"
    ],
    "setup_price": 4995,
    "monthly_price": 699,
    "deliverables": "Conversion, communications, CRM, estimating, proposals, reviews, content, BI",
    "fulfillment_notes": "Managed implementation",
    "status": "DRAFT"
  },
  {
    "package_id": "PKG-004",
    "name": "Commercial Bid System",
    "audience": "Commercial flooring contractors",
    "outcome": "Find, qualify and bid more profitable work",
    "tool_ids": [
      "TOOL-020",
      "TOOL-021",
      "TOOL-022",
      "TOOL-023"
    ],
    "setup_price": 7500,
    "monthly_price": 1299,
    "deliverables": "Discovery, takeoff assistance, bid management, GC CRM",
    "fulfillment_notes": "Human validation mandatory",
    "status": "DRAFT"
  },
  {
    "package_id": "PKG-005",
    "name": "Operations Control System",
    "audience": "Multi-crew contractors",
    "outcome": "Run projects with stronger documentation and margin control",
    "tool_ids": [
      "TOOL-024",
      "TOOL-025",
      "TOOL-026",
      "TOOL-027",
      "TOOL-028",
      "TOOL-029"
    ],
    "setup_price": 3995,
    "monthly_price": 699,
    "deliverables": "Startup, schedule, field reports, change orders, cost and collections",
    "fulfillment_notes": "Accounting integration optional",
    "status": "DRAFT"
  },
  {
    "package_id": "PKG-006",
    "name": "Multi-Location Authority",
    "audience": "Regional contractors",
    "outcome": "Standardize locations and lead routing",
    "tool_ids": [
      "TOOL-033",
      "TOOL-004",
      "TOOL-007",
      "TOOL-009",
      "TOOL-030"
    ],
    "setup_price": 10000,
    "monthly_price": 1999,
    "deliverables": "Location network, SEO, communications, CRM and analytics",
    "fulfillment_notes": "Custom scoping",
    "status": "DRAFT"
  },
  {
    "package_id": "PKG-007",
    "name": "Complete Contractor OS",
    "audience": "Established contractors",
    "outcome": "One connected operating environment",
    "tool_ids": [
      "TOOL-034"
    ],
    "setup_price": 15000,
    "monthly_price": 1999,
    "deliverables": "Website, sales, communications, estimating, operations, analytics and support",
    "fulfillment_notes": "Enterprise onboarding",
    "status": "DRAFT"
  }
];

export const fulfillment = [
  {
    "step_id": "FUL-001",
    "sequence": 10,
    "stage": "Purchase Received",
    "trigger": "Order paid or approved invoice",
    "output": "Create customer, order, entitlement and project",
    "automation": "Commerce automation",
    "human_gate": "Admin review for exceptions",
    "target_sla": "15 min",
    "receipt": "Order receipt",
    "release": "MVP"
  },
  {
    "step_id": "FUL-002",
    "sequence": 20,
    "stage": "Account and Portal Provisioned",
    "trigger": "Valid order",
    "output": "Create portal access and product workspace",
    "automation": "Identity automation",
    "human_gate": "User invitation approved",
    "target_sla": "15 min",
    "receipt": "Provisioning receipt",
    "release": "MVP"
  },
  {
    "step_id": "FUL-003",
    "sequence": 30,
    "stage": "Intake Issued",
    "trigger": "Workspace ready",
    "output": "Send package-specific intake checklist",
    "automation": "Notification automation",
    "human_gate": "No live message without consent",
    "target_sla": "1 hour",
    "receipt": "Notification receipt",
    "release": "MVP"
  },
  {
    "step_id": "FUL-004",
    "sequence": 40,
    "stage": "Intake Validated",
    "trigger": "Customer submits intake",
    "output": "Check completeness, evidence and contradictions",
    "automation": "Validator",
    "human_gate": "Operator resolves missing source truth",
    "target_sla": "4 hours",
    "receipt": "ValidationReceipt",
    "release": "MVP"
  },
  {
    "step_id": "FUL-005",
    "sequence": 50,
    "stage": "Market and Source Research",
    "trigger": "Intake passes",
    "output": "Create audience, market, competitor and positioning packet",
    "automation": "Research agent",
    "human_gate": "Sources reviewed",
    "target_sla": "1 business day",
    "receipt": "Research packet",
    "release": "MVP"
  },
  {
    "step_id": "FUL-006",
    "sequence": 60,
    "stage": "Three Brand Directions",
    "trigger": "Research approved",
    "output": "Generate exactly three brand packs",
    "automation": "Brand generator",
    "human_gate": "Operator curates options",
    "target_sla": "1 business day",
    "receipt": "GenerationRun",
    "release": "MVP"
  },
  {
    "step_id": "FUL-007",
    "sequence": 70,
    "stage": "Customer Brand Approval",
    "trigger": "Options published",
    "output": "Capture decision and revision request",
    "automation": "Approval workflow",
    "human_gate": "Customer decision",
    "target_sla": "3 business days",
    "receipt": "ApprovalReceipt",
    "release": "MVP"
  },
  {
    "step_id": "FUL-008",
    "sequence": 80,
    "stage": "Logo and Brand Assets",
    "trigger": "Brand selected",
    "output": "Generate final logo variants and usage assets",
    "automation": "Media generator",
    "human_gate": "Operator QA",
    "target_sla": "1 business day",
    "receipt": "Asset manifest",
    "release": "MVP"
  },
  {
    "step_id": "FUL-009",
    "sequence": 90,
    "stage": "Three Website Directions",
    "trigger": "Brand assets approved",
    "output": "Generate exactly three website directions",
    "automation": "Website generator",
    "human_gate": "Operator QA",
    "target_sla": "1 business day",
    "receipt": "GenerationRun",
    "release": "MVP"
  },
  {
    "step_id": "FUL-010",
    "sequence": 100,
    "stage": "Customer Website Approval",
    "trigger": "Directions published",
    "output": "Capture selected direction and revisions",
    "automation": "Approval workflow",
    "human_gate": "Customer decision",
    "target_sla": "3 business days",
    "receipt": "ApprovalReceipt",
    "release": "MVP"
  },
  {
    "step_id": "FUL-011",
    "sequence": 110,
    "stage": "Content and Configuration",
    "trigger": "Direction selected",
    "output": "Generate pages, services, forms, integrations and product setup",
    "automation": "Generator swarm",
    "human_gate": "Operator validates claims and routing",
    "target_sla": "2 business days",
    "receipt": "Build packet",
    "release": "MVP"
  },
  {
    "step_id": "FUL-012",
    "sequence": 120,
    "stage": "Preview Assembly",
    "trigger": "Build packet approved",
    "output": "Assemble branch/preview only",
    "automation": "Build agent",
    "human_gate": "No production mutation",
    "target_sla": "1 business day",
    "receipt": "Preview receipt",
    "release": "MVP"
  },
  {
    "step_id": "FUL-013",
    "sequence": 130,
    "stage": "Automated Validation",
    "trigger": "Preview available",
    "output": "Run functional, responsive, accessibility, security and performance tests",
    "automation": "Five-minute validator",
    "human_gate": "Operator reviews blockers",
    "target_sla": "Continuous",
    "receipt": "Validation receipts",
    "release": "MVP"
  },
  {
    "step_id": "FUL-014",
    "sequence": 140,
    "stage": "Customer Preview Review",
    "trigger": "Validation minimum met",
    "output": "Publish desktop, tablet and mobile evidence",
    "automation": "Approval workflow",
    "human_gate": "Customer approval",
    "target_sla": "3 business days",
    "receipt": "ApprovalReceipt",
    "release": "MVP"
  },
  {
    "step_id": "FUL-015",
    "sequence": 150,
    "stage": "Revision Cycle",
    "trigger": "Changes requested",
    "output": "Create bounded revision task and new version",
    "automation": "Queue automation",
    "human_gate": "Operator approves revision scope",
    "target_sla": "1 business day",
    "receipt": "VersionSnapshot",
    "release": "MVP"
  },
  {
    "step_id": "FUL-016",
    "sequence": 160,
    "stage": "Final Launch Approval",
    "trigger": "All revisions accepted",
    "output": "Present launch checklist and rollback",
    "automation": "Release gate",
    "human_gate": "Operator protected approval",
    "target_sla": "Before launch",
    "receipt": "ReleaseCandidate",
    "release": "MVP"
  },
  {
    "step_id": "FUL-017",
    "sequence": 170,
    "stage": "Controlled Release",
    "trigger": "Explicit operator approval",
    "output": "Deploy/promote and run smoke tests",
    "automation": "Release workflow",
    "human_gate": "Protected action",
    "target_sla": "Scheduled",
    "receipt": "Release receipt",
    "release": "MVP"
  },
  {
    "step_id": "FUL-018",
    "sequence": 180,
    "stage": "Training and Handoff",
    "trigger": "Release passes",
    "output": "Provide portal, content, lead and support onboarding",
    "automation": "Customer success",
    "human_gate": "Customer acknowledgment",
    "target_sla": "1 business day",
    "receipt": "Handoff receipt",
    "release": "MVP"
  },
  {
    "step_id": "FUL-019",
    "sequence": 190,
    "stage": "30-Day Optimization",
    "trigger": "30 days live",
    "output": "Review performance, issues, adoption and recommended upgrades",
    "automation": "Customer health workflow",
    "human_gate": "Operator approves offers",
    "target_sla": "Monthly",
    "receipt": "Optimization report",
    "release": "Growth"
  }
];

export const approvals = [
  {
    "approval_id": "APR-001",
    "sequence": 10,
    "stage": "Business Intake",
    "subject_type": "IntakeResponse",
    "customer_role": "Customer",
    "internal_reviewer": "Operator",
    "acceptance_criteria": "Required fields complete and evidence attached",
    "decision_type": "Approval",
    "trigger": "Intake submitted",
    "unlocks": "Brand discovery",
    "severity": "Critical"
  },
  {
    "approval_id": "APR-002",
    "sequence": 20,
    "stage": "Business Name and Positioning",
    "subject_type": "BusinessProject",
    "customer_role": "Customer",
    "internal_reviewer": "Operator",
    "acceptance_criteria": "Name, market, services and promise selected",
    "decision_type": "Approval",
    "trigger": "Discovery complete",
    "unlocks": "Logo options",
    "severity": "High"
  },
  {
    "approval_id": "APR-003",
    "sequence": 30,
    "stage": "Logo Directions",
    "subject_type": "MediaAsset",
    "customer_role": "Customer",
    "internal_reviewer": "Operator",
    "acceptance_criteria": "Exactly three distinct logo directions presented",
    "decision_type": "Approval",
    "trigger": "Three options ready",
    "unlocks": "Logo pack",
    "severity": "Critical"
  },
  {
    "approval_id": "APR-004",
    "sequence": 40,
    "stage": "Logo Pack",
    "subject_type": "MediaAsset",
    "customer_role": "Customer",
    "internal_reviewer": "Operator",
    "acceptance_criteria": "Approved logo exported in required variants",
    "decision_type": "Approval",
    "trigger": "Logo direction approved",
    "unlocks": "Brand packs",
    "severity": "Critical"
  },
  {
    "approval_id": "APR-005",
    "sequence": 50,
    "stage": "Brand Packs",
    "subject_type": "BrandPack",
    "customer_role": "Customer",
    "internal_reviewer": "Operator",
    "acceptance_criteria": "Exactly three complete brand packs presented",
    "decision_type": "Approval",
    "trigger": "Logo pack approved",
    "unlocks": "Website directions",
    "severity": "Critical"
  },
  {
    "approval_id": "APR-006",
    "sequence": 60,
    "stage": "Website Directions",
    "subject_type": "WebsiteProject",
    "customer_role": "Customer",
    "internal_reviewer": "Operator",
    "acceptance_criteria": "Exactly three website/content directions presented",
    "decision_type": "Approval",
    "trigger": "Brand pack approved",
    "unlocks": "Workflow options",
    "severity": "Critical"
  },
  {
    "approval_id": "APR-007",
    "sequence": 70,
    "stage": "Workflow Options",
    "subject_type": "OperatingProcedure",
    "customer_role": "Customer",
    "internal_reviewer": "Operator",
    "acceptance_criteria": "Exactly three fulfillment/automation directions presented",
    "decision_type": "Approval",
    "trigger": "Website direction approved",
    "unlocks": "Information architecture",
    "severity": "Critical"
  },
  {
    "approval_id": "APR-008",
    "sequence": 80,
    "stage": "Page Map and Services",
    "subject_type": "WebsitePage",
    "customer_role": "Customer",
    "internal_reviewer": "Operator",
    "acceptance_criteria": "Routes, services and CTAs are accurate",
    "decision_type": "Approval",
    "trigger": "Direction selected",
    "unlocks": "Copy generation",
    "severity": "High"
  },
  {
    "approval_id": "APR-009",
    "sequence": 90,
    "stage": "Homepage and Core Copy",
    "subject_type": "WebsitePage",
    "customer_role": "Customer",
    "internal_reviewer": "Operator",
    "acceptance_criteria": "Claims are supported and messaging is approved",
    "decision_type": "Approval",
    "trigger": "IA approved",
    "unlocks": "Media selection",
    "severity": "High"
  },
  {
    "approval_id": "APR-010",
    "sequence": 100,
    "stage": "Images and Galleries",
    "subject_type": "MediaAsset",
    "customer_role": "Customer",
    "internal_reviewer": "Operator",
    "acceptance_criteria": "Verified projects separated from disclosed concepts",
    "decision_type": "Approval",
    "trigger": "Copy approved",
    "unlocks": "Functional configuration",
    "severity": "High"
  },
  {
    "approval_id": "APR-011",
    "sequence": 110,
    "stage": "Forms and Lead Routing",
    "subject_type": "IntegrationConnection",
    "customer_role": "Customer",
    "internal_reviewer": "Operator",
    "acceptance_criteria": "Destination, consent, notifications and fallback tested",
    "decision_type": "Approval",
    "trigger": "Functional setup complete",
    "unlocks": "Responsive preview",
    "severity": "Critical"
  },
  {
    "approval_id": "APR-012",
    "sequence": 120,
    "stage": "Estimator and Pricing Rules",
    "subject_type": "PricingSetting",
    "customer_role": "Customer",
    "internal_reviewer": "Operator",
    "acceptance_criteria": "Rates, scope, disclaimers and review triggers approved",
    "decision_type": "Approval",
    "trigger": "Estimator configured",
    "unlocks": "Communications",
    "severity": "Critical"
  },
  {
    "approval_id": "APR-013",
    "sequence": 130,
    "stage": "Communications and Consent",
    "subject_type": "ConsentRecord",
    "customer_role": "Customer",
    "internal_reviewer": "Operator",
    "acceptance_criteria": "Numbers, templates, consent and opt-out approved",
    "decision_type": "Approval",
    "trigger": "Provider setup ready",
    "unlocks": "Responsive preview",
    "severity": "Critical"
  },
  {
    "approval_id": "APR-014",
    "sequence": 140,
    "stage": "Desktop Preview",
    "subject_type": "ReleaseCandidate",
    "customer_role": "Customer",
    "internal_reviewer": "Validator",
    "acceptance_criteria": "Desktop screenshot and functional receipt pass",
    "decision_type": "Approval",
    "trigger": "Preview deployed",
    "unlocks": "Tablet preview",
    "severity": "Critical"
  },
  {
    "approval_id": "APR-015",
    "sequence": 150,
    "stage": "Tablet Preview",
    "subject_type": "ReleaseCandidate",
    "customer_role": "Customer",
    "internal_reviewer": "Validator",
    "acceptance_criteria": "Tablet screenshot and functional receipt pass",
    "decision_type": "Approval",
    "trigger": "Desktop approved",
    "unlocks": "Mobile preview",
    "severity": "Critical"
  },
  {
    "approval_id": "APR-016",
    "sequence": 160,
    "stage": "Mobile Preview",
    "subject_type": "ReleaseCandidate",
    "customer_role": "Customer",
    "internal_reviewer": "Validator",
    "acceptance_criteria": "Mobile screenshot, PWA and tap targets pass",
    "decision_type": "Approval",
    "trigger": "Tablet approved",
    "unlocks": "Final release review",
    "severity": "Critical"
  },
  {
    "approval_id": "APR-017",
    "sequence": 170,
    "stage": "Domain and Launch Checklist",
    "subject_type": "DomainConnection",
    "customer_role": "Customer",
    "internal_reviewer": "Operator",
    "acceptance_criteria": "Domain, DNS plan, analytics and rollback confirmed",
    "decision_type": "Approval",
    "trigger": "All previews approved",
    "unlocks": "Final release",
    "severity": "Critical"
  },
  {
    "approval_id": "APR-018",
    "sequence": 180,
    "stage": "Final Release",
    "subject_type": "ReleaseCandidate",
    "customer_role": "Operator",
    "internal_reviewer": "Validator",
    "acceptance_criteria": "All gates pass and rollback is verified",
    "decision_type": "Protected approval",
    "trigger": "Launch checklist approved",
    "unlocks": "Production release",
    "severity": "Critical"
  }
];

export const automations = [
  {
    "automation_id": "AUTO-001",
    "workflow": "Order Provisioning",
    "trigger": "payment.succeeded",
    "mode": "Event",
    "action": "Create customer account, order, entitlements and project records.",
    "core_data": "CartOrder; CustomerAccount; ProductEntitlement",
    "connectors": "Identity; billing",
    "output": "Customer workspace",
    "target_sla": "Immediate",
    "max_retries": "3",
    "idempotency_key": "OrderProvision:{order_id}",
    "owner": "Admin",
    "protected_action": "No",
    "receipt": "ActionReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-002",
    "workflow": "Abandoned Checkout",
    "trigger": "checkout.abandoned",
    "mode": "Event",
    "action": "Create reminder task after consent and delay.",
    "core_data": "CartOrder; ConsentRecord",
    "connectors": "Billing; notifications",
    "output": "Draft reminder",
    "target_sla": "1 hour",
    "max_retries": "2",
    "idempotency_key": "Abandoned:{order_id}:{day}",
    "owner": "Sales",
    "protected_action": "Yes - customer message",
    "receipt": "NotificationReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-003",
    "workflow": "Intake Completeness Validator",
    "trigger": "intake.submitted",
    "mode": "Event + 5-minute validator",
    "action": "Validate required fields, files, consent and contradictions.",
    "core_data": "IntakeResponse; BusinessProject",
    "connectors": "Files; rules",
    "output": "ValidationReceipt",
    "target_sla": "5 minutes",
    "max_retries": "3",
    "idempotency_key": "Intake:{project_id}:{version}",
    "owner": "Operator",
    "protected_action": "No",
    "receipt": "ValidationReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-004",
    "workflow": "Approval Reminder",
    "trigger": "approval.pending",
    "mode": "Hourly",
    "action": "Remind customer based on SLA and consent.",
    "core_data": "Approval; ConsentRecord",
    "connectors": "Email/SMS",
    "output": "Reminder draft or approved send",
    "target_sla": "Hourly",
    "max_retries": "3",
    "idempotency_key": "ApprovalReminder:{approval_id}:{day}",
    "owner": "Customer Success",
    "protected_action": "Yes - live message",
    "receipt": "NotificationReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-005",
    "workflow": "Revision Queue",
    "trigger": "approval.changes_requested",
    "mode": "Event",
    "action": "Create bounded revision task and version snapshot.",
    "core_data": "Approval; ProjectTask; VersionSnapshot",
    "connectors": "Generator queue",
    "output": "Revision task",
    "target_sla": "Immediate",
    "max_retries": "2",
    "idempotency_key": "Revision:{approval_id}:{version}",
    "owner": "Operator",
    "protected_action": "No",
    "receipt": "ActionReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-006",
    "workflow": "Brand Generation Router",
    "trigger": "brand.research_approved",
    "mode": "Event",
    "action": "Route approved intake to three-option brand generator.",
    "core_data": "BusinessProject; ResearchSource",
    "connectors": "AI gateway",
    "output": "3 BrandPack records",
    "target_sla": "Immediate",
    "max_retries": "2",
    "idempotency_key": "Brand:{project_id}:{version}",
    "owner": "Operator",
    "protected_action": "No",
    "receipt": "GenerationRun",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-007",
    "workflow": "Logo Generation Router",
    "trigger": "logo.direction_requested",
    "mode": "Event",
    "action": "Create three logo directions and media QA jobs.",
    "core_data": "BrandPack; VisualPrompt",
    "connectors": "Media provider",
    "output": "Media assets",
    "target_sla": "Immediate",
    "max_retries": "2",
    "idempotency_key": "Logo:{project_id}:{version}",
    "owner": "Operator",
    "protected_action": "No",
    "receipt": "GenerationRun",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-008",
    "workflow": "Website Direction Router",
    "trigger": "website.direction_requested",
    "mode": "Event",
    "action": "Generate three website/content directions using approved brand.",
    "core_data": "BrandPack; WebsiteProject",
    "connectors": "Prompt router",
    "output": "3 WebsiteProject candidates",
    "target_sla": "Immediate",
    "max_retries": "2",
    "idempotency_key": "WebDirection:{project_id}:{version}",
    "owner": "Operator",
    "protected_action": "No",
    "receipt": "GenerationRun",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-009",
    "workflow": "Preview Build Queue",
    "trigger": "website.direction_approved",
    "mode": "Event",
    "action": "Create branch-safe website build job.",
    "core_data": "WebsiteProject; WebsitePage",
    "connectors": "GitHub; Base44/Vercel",
    "output": "Preview candidate",
    "target_sla": "Immediate",
    "max_retries": "2",
    "idempotency_key": "Preview:{project_id}:{version}",
    "owner": "Operator",
    "protected_action": "Yes - code write",
    "receipt": "ActionReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-010",
    "workflow": "Five-Minute Validation Heartbeat",
    "trigger": "schedule",
    "mode": "Every 5 minutes",
    "action": "Check queued jobs, stale leases, missing receipts, preview health and protected actions.",
    "core_data": "AgentJob; ValidationReceipt; ApprovalReceipt",
    "connectors": "Vercel Workflow",
    "output": "Validation and escalation records",
    "target_sla": "5 minutes",
    "max_retries": "3",
    "idempotency_key": "Validator:{run_slot}",
    "owner": "Validator",
    "protected_action": "No",
    "receipt": "ValidationReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-011",
    "workflow": "Responsive Screenshot Runner",
    "trigger": "preview.ready",
    "mode": "Event + retry",
    "action": "Capture desktop, tablet and mobile screenshots.",
    "core_data": "ReleaseCandidate",
    "connectors": "Playwright",
    "output": "Screenshot evidence",
    "target_sla": "Immediate",
    "max_retries": "2",
    "idempotency_key": "Screenshot:{candidate_id}:{viewport}",
    "owner": "Validator",
    "protected_action": "No",
    "receipt": "EvidenceArtifact",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-012",
    "workflow": "Functional Route Tester",
    "trigger": "preview.ready",
    "mode": "Event + retry",
    "action": "Test routes, forms, auth boundaries, links and errors.",
    "core_data": "ReleaseCandidate; WebsitePage",
    "connectors": "Playwright",
    "output": "Test receipts",
    "target_sla": "Immediate",
    "max_retries": "2",
    "idempotency_key": "RouteTest:{candidate_id}:{suite}",
    "owner": "Validator",
    "protected_action": "No",
    "receipt": "ValidationReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-013",
    "workflow": "Release Gate Evaluator",
    "trigger": "validation.updated",
    "mode": "Event",
    "action": "Calculate whether all required gates pass.",
    "core_data": "ValidationReceipt; ApprovalReceipt",
    "connectors": "Rules engine",
    "output": "ReleaseCandidate state",
    "target_sla": "Immediate",
    "max_retries": "5",
    "idempotency_key": "Gate:{candidate_id}:{version}",
    "owner": "Validator",
    "protected_action": "No",
    "receipt": "ValidationReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-014",
    "workflow": "Production Release",
    "trigger": "release.approved",
    "mode": "Protected event",
    "action": "Promote only the approved candidate and run smoke tests.",
    "core_data": "ReleaseCandidate; ApprovalReceipt",
    "connectors": "GitHub; Vercel",
    "output": "Production release",
    "target_sla": "Scheduled",
    "max_retries": "1",
    "idempotency_key": "Release:{candidate_id}:{approval_id}",
    "owner": "Operator",
    "protected_action": "Yes - production",
    "receipt": "ReleaseReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-015",
    "workflow": "Rollback Trigger",
    "trigger": "release.failed",
    "mode": "Condition",
    "action": "Restore last known good deployment after protected approval or pre-authorized rule.",
    "core_data": "ReleaseCandidate; ApprovalReceipt",
    "connectors": "Vercel",
    "output": "Rollback",
    "target_sla": "Immediate",
    "max_retries": "1",
    "idempotency_key": "Rollback:{release_id}",
    "owner": "Operator",
    "protected_action": "Yes - production",
    "receipt": "RollbackReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-016",
    "workflow": "Missed-Call Recovery",
    "trigger": "call.missed",
    "mode": "Event",
    "action": "Verify consent state and send approved text-back workflow.",
    "core_data": "Call; Contact; ConsentRecord",
    "connectors": "Twilio",
    "output": "SMS and lead update",
    "target_sla": "1 minute",
    "max_retries": "3",
    "idempotency_key": "MissedCall:{call_sid}",
    "owner": "Customer",
    "protected_action": "Yes - customer message",
    "receipt": "MessageReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-017",
    "workflow": "Lead Response SLA",
    "trigger": "lead.created",
    "mode": "Event + 5-minute check",
    "action": "Track response time, escalate overdue leads and recommend next action.",
    "core_data": "Lead; Activity",
    "connectors": "CRM; notifications",
    "output": "Task/escalation",
    "target_sla": "5 minutes",
    "max_retries": "3",
    "idempotency_key": "LeadSLA:{lead_id}",
    "owner": "Customer",
    "protected_action": "Optional message",
    "receipt": "ValidationReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-018",
    "workflow": "Estimate Follow-Up",
    "trigger": "proposal.sent",
    "mode": "Scheduled sequence",
    "action": "Create consent-aware follow-up sequence and stop on response or status change.",
    "core_data": "Proposal; Deal; ConsentRecord",
    "connectors": "SMS/email",
    "output": "Follow-up events",
    "target_sla": "Daily",
    "max_retries": "3",
    "idempotency_key": "ProposalFU:{proposal_id}:{step}",
    "owner": "Customer",
    "protected_action": "Yes - customer message",
    "receipt": "MessageReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-019",
    "workflow": "Review Request",
    "trigger": "project.completed",
    "mode": "Delayed event",
    "action": "Request review after customer completion acknowledgment.",
    "core_data": "Project; Contact; ConsentRecord",
    "connectors": "SMS/email",
    "output": "Review request",
    "target_sla": "24 hours",
    "max_retries": "2",
    "idempotency_key": "Review:{project_id}:{contact_id}",
    "owner": "Customer",
    "protected_action": "Yes - customer message",
    "receipt": "MessageReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-020",
    "workflow": "Usage Meter Aggregation",
    "trigger": "usage.event",
    "mode": "Hourly",
    "action": "Aggregate communications, AI, storage and product usage.",
    "core_data": "Event; UsageMeter",
    "connectors": "Provider APIs",
    "output": "Usage totals",
    "target_sla": "Hourly",
    "max_retries": "3",
    "idempotency_key": "Usage:{account_id}:{period}",
    "owner": "Billing",
    "protected_action": "No",
    "receipt": "UsageReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-021",
    "workflow": "Overage Alert",
    "trigger": "usage.threshold_reached",
    "mode": "Event",
    "action": "Notify account before overage and recommend plan change.",
    "core_data": "UsageMeter; Subscription",
    "connectors": "Notifications",
    "output": "Alert and recommendation",
    "target_sla": "Immediate",
    "max_retries": "2",
    "idempotency_key": "Overage:{account_id}:{metric}:{period}",
    "owner": "Billing",
    "protected_action": "Yes - account message",
    "receipt": "NotificationReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-022",
    "workflow": "Contextual Upgrade Engine",
    "trigger": "customer.health_updated",
    "mode": "Daily",
    "action": "Evaluate verified triggers and create transparent recommendations.",
    "core_data": "ToolRecommendation; Event; AiTool",
    "connectors": "Rules/AI",
    "output": "Upgrade recommendation",
    "target_sla": "Daily",
    "max_retries": "2",
    "idempotency_key": "Upgrade:{account_id}:{date}",
    "owner": "Customer Success",
    "protected_action": "No auto-purchase",
    "receipt": "RecommendationReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-023",
    "workflow": "Payment Dunning",
    "trigger": "invoice.failed",
    "mode": "Scheduled",
    "action": "Retry and notify according to approved billing policy.",
    "core_data": "BillingRecord; Subscription",
    "connectors": "Payment provider",
    "output": "Dunning status",
    "target_sla": "Daily",
    "max_retries": "3",
    "idempotency_key": "Dunning:{invoice_id}:{attempt}",
    "owner": "Billing",
    "protected_action": "Yes - account message",
    "receipt": "BillingReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-024",
    "workflow": "Support Triage",
    "trigger": "ticket.created",
    "mode": "Event",
    "action": "Classify ticket, suggest knowledge answer and escalate urgent cases.",
    "core_data": "SupportTicket; KnowledgeArticle",
    "connectors": "AI gateway",
    "output": "Draft answer and priority",
    "target_sla": "Immediate",
    "max_retries": "2",
    "idempotency_key": "Support:{ticket_id}:{version}",
    "owner": "Support",
    "protected_action": "No auto-send by default",
    "receipt": "SupportReceipt",
    "status": "PLANNED"
  },
  {
    "automation_id": "AUTO-025",
    "workflow": "Customer Health Review",
    "trigger": "schedule",
    "mode": "Weekly",
    "action": "Score onboarding, adoption, lead response, approvals, support and billing.",
    "core_data": "Event; UsageMeter; SupportTicket",
    "connectors": "Analytics",
    "output": "Customer health record",
    "target_sla": "Weekly",
    "max_retries": "2",
    "idempotency_key": "Health:{account_id}:{week}",
    "owner": "Customer Success",
    "protected_action": "No",
    "receipt": "ReportSnapshot",
    "status": "PLANNED"
  }
];

export const modules = [
  {
    "module_id": "MOD-001",
    "name": "Public Marketing Website",
    "domain": "Acquisition",
    "purpose": "Home, solutions, tools marketplace, packages, pricing, case studies, FAQs and legal pages.",
    "primary_user": "Visitor",
    "surface": "Public site",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "WebsitePage; AiTool; ToolBundle",
    "dependencies": "SEO, analytics, CMS",
    "priority": "High"
  },
  {
    "module_id": "MOD-002",
    "name": "Authentication",
    "domain": "Identity",
    "purpose": "Sign up, sign in, password recovery, session and role enforcement.",
    "primary_user": "All users",
    "surface": "Auth",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "User; CustomerAccount",
    "dependencies": "Auth provider, email",
    "priority": "Critical"
  },
  {
    "module_id": "MOD-003",
    "name": "Customer Portal Shell",
    "domain": "Portal",
    "purpose": "Navigation, account switcher, status, notifications and help.",
    "primary_user": "Customer",
    "surface": "Portal",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "CustomerAccount; Notification",
    "dependencies": "Auth, support",
    "priority": "Critical"
  },
  {
    "module_id": "MOD-004",
    "name": "Customer Dashboard",
    "domain": "Portal",
    "purpose": "Business summary, purchased products, project progress, leads, messages, usage and upgrades.",
    "primary_user": "Customer",
    "surface": "Dashboard",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "StudentProfile; CartOrder; ToolRecommendation",
    "dependencies": "Analytics, entitlements",
    "priority": "Critical"
  },
  {
    "module_id": "MOD-005",
    "name": "AI Tool Marketplace",
    "domain": "Commerce",
    "purpose": "Problem-led catalog of tools, bundles, add-ons and managed services.",
    "primary_user": "Visitor; Customer",
    "surface": "Marketplace",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "AiTool; ToolBundle; Offer",
    "dependencies": "Checkout, entitlements",
    "priority": "Critical"
  },
  {
    "module_id": "MOD-006",
    "name": "Pricing and Checkout",
    "domain": "Commerce",
    "purpose": "Package comparison, setup/monthly/usage pricing, checkout and order receipt.",
    "primary_user": "Visitor; Customer",
    "surface": "Pricing",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "CartOrder; BillingRecord; Subscription",
    "dependencies": "Stripe/Square",
    "priority": "Critical"
  },
  {
    "module_id": "MOD-007",
    "name": "Business Diagnostic",
    "domain": "Sales",
    "purpose": "Questionnaire that recommends tools by stage, pain, goals and budget.",
    "primary_user": "Visitor; Customer",
    "surface": "Advisor",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "ToolRecommendation; IntakeResponse",
    "dependencies": "Recommendation engine",
    "priority": "High"
  },
  {
    "module_id": "MOD-008",
    "name": "Onboarding and Intake",
    "domain": "Fulfillment",
    "purpose": "Business, market, services, assets, access, consent and package intake.",
    "primary_user": "Customer; Operator",
    "surface": "Intake",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "BusinessProject; IntakeResponse",
    "dependencies": "Files, email",
    "priority": "Critical"
  },
  {
    "module_id": "MOD-009",
    "name": "Approval Center",
    "domain": "Fulfillment",
    "purpose": "Versioned approvals for names, logos, brands, websites, copy, media, forms and launch.",
    "primary_user": "Customer; Operator",
    "surface": "Approvals",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "Approval; ApprovalReceipt; VersionSnapshot",
    "dependencies": "Notifications",
    "priority": "Critical"
  },
  {
    "module_id": "MOD-010",
    "name": "Logo Generator Operations",
    "domain": "Generator",
    "purpose": "Internal queue and customer approval for three logo directions and final packs.",
    "primary_user": "Operator",
    "surface": "Generator Ops",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "GenerationRun; MediaAsset; Approval",
    "dependencies": "Image provider",
    "priority": "High"
  },
  {
    "module_id": "MOD-011",
    "name": "Brand Pack Generator Operations",
    "domain": "Generator",
    "purpose": "Three brand directions, colors, typography, messaging and usage rules.",
    "primary_user": "Operator",
    "surface": "Generator Ops",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "BrandPack; Approval",
    "dependencies": "Prompt router",
    "priority": "High"
  },
  {
    "module_id": "MOD-012",
    "name": "Website Generator Operations",
    "domain": "Generator",
    "purpose": "Template selection, content assembly, preview, validation, revision and release.",
    "primary_user": "Operator",
    "surface": "Generator Ops",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "WebsiteProject; WebsitePage; GenerationRun",
    "dependencies": "GitHub, Vercel",
    "priority": "Critical"
  },
  {
    "module_id": "MOD-013",
    "name": "Communication Center",
    "domain": "Communications",
    "purpose": "Unified SMS, voice, WhatsApp, email, consent, templates and message history.",
    "primary_user": "Customer; Staff",
    "surface": "Communications",
    "release": "Growth",
    "status": "PLANNED",
    "core_entities": "Message; Channel; ConsentRecord",
    "dependencies": "Twilio, SendGrid/Gmail",
    "priority": "Critical"
  },
  {
    "module_id": "MOD-014",
    "name": "AI Receptionist",
    "domain": "Communications",
    "purpose": "Inbound voice, qualification, routing, summaries, booking and escalation.",
    "primary_user": "Customer",
    "surface": "Voice",
    "release": "Growth",
    "status": "PLANNED",
    "core_entities": "Call; Lead; Contact",
    "dependencies": "Twilio Voice, AI gateway",
    "priority": "High"
  },
  {
    "module_id": "MOD-015",
    "name": "CRM and Lead Pipeline",
    "domain": "Sales",
    "purpose": "Lead capture, qualification, opportunities, follow-up, source attribution and conversion.",
    "primary_user": "Customer",
    "surface": "CRM",
    "release": "Growth",
    "status": "PLANNED",
    "core_entities": "Lead; Deal; Contact",
    "dependencies": "Forms, communications",
    "priority": "Critical"
  },
  {
    "module_id": "MOD-016",
    "name": "Estimator and Proposal",
    "domain": "Sales",
    "purpose": "Guided intake, preliminary range, proposal, acceptance and deposit.",
    "primary_user": "Customer",
    "surface": "Sales",
    "release": "Growth",
    "status": "PLANNED",
    "core_entities": "PricingSetting; Proposal; BillingRecord",
    "dependencies": "Payments, e-sign",
    "priority": "High"
  },
  {
    "module_id": "MOD-017",
    "name": "Review and Referral Automation",
    "domain": "Marketing",
    "purpose": "Completion-triggered review and referral requests with opt-out handling.",
    "primary_user": "Customer",
    "surface": "Reputation",
    "release": "Growth",
    "status": "PLANNED",
    "core_entities": "Campaign; Contact; ConsentRecord",
    "dependencies": "SMS, email",
    "priority": "High"
  },
  {
    "module_id": "MOD-018",
    "name": "Social and Content Studio",
    "domain": "Marketing",
    "purpose": "Content calendar, captions, images, video scripts and approval queues.",
    "primary_user": "Customer; Operator",
    "surface": "Content",
    "release": "Growth",
    "status": "PLANNED",
    "core_entities": "ContentAsset; Campaign; MediaAsset",
    "dependencies": "Social adapters",
    "priority": "Medium"
  },
  {
    "module_id": "MOD-019",
    "name": "Local SEO and Website Growth",
    "domain": "Marketing",
    "purpose": "Service/location pages, GBP content, citations, schema and performance reporting.",
    "primary_user": "Customer",
    "surface": "SEO",
    "release": "Growth",
    "status": "PLANNED",
    "core_entities": "WebsitePage; MarketFinding",
    "dependencies": "Search tools",
    "priority": "High"
  },
  {
    "module_id": "MOD-020",
    "name": "Floor Visualizer",
    "domain": "Sales",
    "purpose": "Customer photo upload, floor mask, finish concepts, comparison and lead handoff.",
    "primary_user": "Visitor; Customer",
    "surface": "Visualizer",
    "release": "Growth",
    "status": "PLANNED",
    "core_entities": "MediaGenerationJob; MediaAsset; Lead",
    "dependencies": "Storage, image provider",
    "priority": "High"
  },
  {
    "module_id": "MOD-021",
    "name": "Commercial BidFast Suite",
    "domain": "Commercial",
    "purpose": "Opportunity discovery, documents, takeoff, proposals and GC pipeline.",
    "primary_user": "Commercial customer",
    "surface": "BidFast",
    "release": "Advanced",
    "status": "PLANNED",
    "core_entities": "Opportunity; Takeoff; Bid; Proposal",
    "dependencies": "Sources, Drive",
    "priority": "High"
  },
  {
    "module_id": "MOD-022",
    "name": "Job Operations",
    "domain": "Operations",
    "purpose": "Project startup, schedule, crew, materials, photos, approvals, changes and completion.",
    "primary_user": "Customer",
    "surface": "Operations",
    "release": "Advanced",
    "status": "PLANNED",
    "core_entities": "Project; WorkOrder; FieldReport",
    "dependencies": "Calendar, storage",
    "priority": "High"
  },
  {
    "module_id": "MOD-023",
    "name": "Business Intelligence",
    "domain": "Analytics",
    "purpose": "Lead, sales, revenue, margin, usage, customer health and product adoption.",
    "primary_user": "Customer; Admin",
    "surface": "Analytics",
    "release": "Growth",
    "status": "PLANNED",
    "core_entities": "ReportSnapshot; Event",
    "dependencies": "Warehouse/analytics",
    "priority": "High"
  },
  {
    "module_id": "MOD-024",
    "name": "Support and Knowledge Base",
    "domain": "Support",
    "purpose": "Tickets, product guidance, how-to content, account help and escalations.",
    "primary_user": "Customer; Staff",
    "surface": "Support",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "SupportTicket; KnowledgeArticle",
    "dependencies": "Email/chat",
    "priority": "High"
  },
  {
    "module_id": "MOD-025",
    "name": "Admin Control Center",
    "domain": "Administration",
    "purpose": "Products, pricing, customers, orders, queues, approvals, integrations, usage, QA and releases.",
    "primary_user": "Admin; Operator",
    "surface": "Admin",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "All core entities",
    "dependencies": "All connectors",
    "priority": "Critical"
  },
  {
    "module_id": "MOD-026",
    "name": "Automation Orchestrator",
    "domain": "Automation",
    "purpose": "Event workflows, five-minute validator, queues, retries, idempotency, receipts and escalations.",
    "primary_user": "System; Operator",
    "surface": "Automation",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "AgentJob; AuditLog; ValidationReceipt",
    "dependencies": "Vercel Workflow",
    "priority": "Critical"
  },
  {
    "module_id": "MOD-027",
    "name": "Entitlements and Usage",
    "domain": "Commerce",
    "purpose": "Product access, feature limits, included units, overages and suspension.",
    "primary_user": "System; Admin",
    "surface": "Billing",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "ProductEntitlement; UsageMeter; Subscription",
    "dependencies": "Billing, communications",
    "priority": "Critical"
  },
  {
    "module_id": "MOD-028",
    "name": "Release and Rollback",
    "domain": "Governance",
    "purpose": "Preview gates, validation evidence, operator approval, release receipt and rollback.",
    "primary_user": "Operator",
    "surface": "Release",
    "release": "MVP",
    "status": "PLANNED",
    "core_entities": "ReleaseCandidate; ApprovalReceipt",
    "dependencies": "GitHub, Vercel",
    "priority": "Critical"
  }
];

export const personas = [
  {
    "persona_id": "PER-001",
    "name": "New PCU Student",
    "business_stage": "Pre-launch",
    "situation": "No brand, website, CRM or portfolio; limited budget and business experience.",
    "desired_outcome": "Launch professionally; get first leads",
    "pain_points": "Confusion, low credibility, scattered setup",
    "likely_first_purchase": "PCU Launch System",
    "likely_upgrades": "Website, logo, brand, intake, review starter",
    "purchase_probability": "High",
    "retention_potential": "High",
    "support_need": "Guided onboarding, milestones, education"
  },
  {
    "persona_id": "PER-002",
    "name": "PCU Graduate / Owner Operator",
    "business_stage": "Early revenue",
    "situation": "Works in field and handles calls, estimates and marketing personally.",
    "desired_outcome": "Capture leads and save nights",
    "pain_points": "Missed calls, slow estimates, weak follow-up",
    "likely_first_purchase": "Lead Capture System",
    "likely_upgrades": "AI receptionist, missed-call text, estimator",
    "purchase_probability": "Very High",
    "retention_potential": "High",
    "support_need": "Mobile-first, managed setup"
  },
  {
    "persona_id": "PER-003",
    "name": "Small Growth Contractor",
    "business_stage": "2-10 employees",
    "situation": "Multiple jobs, part-time office help, inconsistent systems.",
    "desired_outcome": "More predictable sales and operations",
    "pain_points": "Scheduling, CRM gaps, inconsistent communication",
    "likely_first_purchase": "Contractor Growth System",
    "likely_upgrades": "CRM, automations, reviews, dashboard",
    "purchase_probability": "Very High",
    "retention_potential": "Very High",
    "support_need": "Role-based portal and reporting"
  },
  {
    "persona_id": "PER-004",
    "name": "Established Local Contractor",
    "business_stage": "Mature local",
    "situation": "Existing website and tools but weak integration and reporting.",
    "desired_outcome": "Improve conversion and reduce admin",
    "pain_points": "Fragmented software, low visibility, duplicate work",
    "likely_first_purchase": "Website Upgrade + Automation",
    "likely_upgrades": "Conversion, integrations, BI, nurture",
    "purchase_probability": "High",
    "retention_potential": "Very High",
    "support_need": "Migration and connector support"
  },
  {
    "persona_id": "PER-005",
    "name": "Commercial Flooring Contractor",
    "business_stage": "Commercial bidder",
    "situation": "Plan/spec workflow, GC relationships, deadlines, addenda and compliance.",
    "desired_outcome": "Find and win profitable projects",
    "pain_points": "Manual discovery, takeoffs, bid tracking",
    "likely_first_purchase": "Commercial Bid System",
    "likely_upgrades": "BidFast, takeoff, proposal, GC CRM",
    "purchase_probability": "High",
    "retention_potential": "Very High",
    "support_need": "Evidence, review gates, document controls"
  },
  {
    "persona_id": "PER-006",
    "name": "Regional / Multi-Location Contractor",
    "business_stage": "Scale stage",
    "situation": "Multiple locations, crews and territories with central management.",
    "desired_outcome": "Standardize and expand",
    "pain_points": "Routing, reporting, brand drift, governance",
    "likely_first_purchase": "Multi-Location Authority",
    "likely_upgrades": "Location sites, routing, analytics, governance",
    "purchase_probability": "Medium",
    "retention_potential": "Very High",
    "support_need": "Multi-tenant controls and SLAs"
  },
  {
    "persona_id": "PER-007",
    "name": "XPS Product Customer",
    "business_stage": "Product-led",
    "situation": "Already buys equipment/materials but may have weak digital operations.",
    "desired_outcome": "Grow business using XPS ecosystem",
    "pain_points": "No organized marketing or sales stack",
    "likely_first_purchase": "XPS Customer Growth Pack",
    "likely_upgrades": "Website upgrade, estimator, content, support",
    "purchase_probability": "High",
    "retention_potential": "High",
    "support_need": "Purchase-history-based recommendations"
  }
];

export const neededEntities = [
  {
    "name": "CustomerAccount",
    "purpose": "Tenant/customer account, business profile and lifecycle status",
    "priority": "Critical",
    "release": "MVP"
  },
  {
    "name": "Subscription",
    "purpose": "Plan, status, billing period, renewal and cancellation",
    "priority": "Critical",
    "release": "MVP"
  },
  {
    "name": "ProductEntitlement",
    "purpose": "Account access to a tool, limits and effective dates",
    "priority": "Critical",
    "release": "MVP"
  },
  {
    "name": "UsageMeter",
    "purpose": "Usage metric, period, included units, consumed and overage",
    "priority": "Critical",
    "release": "MVP"
  },
  {
    "name": "PaymentMethod",
    "purpose": "Provider reference and display-safe payment method details",
    "priority": "Critical",
    "release": "MVP"
  },
  {
    "name": "InvoiceLine",
    "purpose": "Line-level setup, subscription, usage, discount and tax details",
    "priority": "High",
    "release": "MVP"
  },
  {
    "name": "RefundRecord",
    "purpose": "Refund request, provider reference, approval and outcome",
    "priority": "High",
    "release": "MVP"
  },
  {
    "name": "DunningAttempt",
    "purpose": "Failed payment retry and notification history",
    "priority": "High",
    "release": "MVP"
  },
  {
    "name": "RevisionRequest",
    "purpose": "Artifact version, requested change, scope and status",
    "priority": "Critical",
    "release": "MVP"
  },
  {
    "name": "ApprovalComment",
    "purpose": "Threaded customer/operator comments on approvals",
    "priority": "High",
    "release": "MVP"
  },
  {
    "name": "SupportTicket",
    "purpose": "Category, priority, account, product, SLA and resolution",
    "priority": "Critical",
    "release": "MVP"
  },
  {
    "name": "KnowledgeArticle",
    "purpose": "Approved customer support and product documentation",
    "priority": "High",
    "release": "MVP"
  },
  {
    "name": "ConsentRecord",
    "purpose": "Channel-specific consent, source, timestamp, scope and revocation",
    "priority": "Critical",
    "release": "MVP"
  },
  {
    "name": "Call",
    "purpose": "Voice call metadata, status, recording consent and summary",
    "priority": "Critical",
    "release": "Growth"
  },
  {
    "name": "Conversation",
    "purpose": "Cross-channel customer conversation and assigned owner",
    "priority": "High",
    "release": "Growth"
  },
  {
    "name": "Notification",
    "purpose": "In-app/email/SMS notification, status and preference",
    "priority": "High",
    "release": "MVP"
  },
  {
    "name": "IntegrationConnection",
    "purpose": "Provider connection, scopes, status and last health check",
    "priority": "Critical",
    "release": "MVP"
  },
  {
    "name": "DomainConnection",
    "purpose": "Domain, DNS requirements, validation and environment",
    "priority": "High",
    "release": "MVP"
  },
  {
    "name": "Event",
    "purpose": "Canonical product, funnel, usage and workflow event",
    "priority": "Critical",
    "release": "MVP"
  },
  {
    "name": "FeatureFlag",
    "purpose": "Account/role/environment feature rollout controls",
    "priority": "High",
    "release": "MVP"
  },
  {
    "name": "ServicePlan",
    "purpose": "Canonical plan definitions and included entitlements",
    "priority": "Critical",
    "release": "MVP"
  },
  {
    "name": "ReleaseCandidate",
    "purpose": "Version, preview, validation summary and approval state",
    "priority": "Critical",
    "release": "MVP"
  },
  {
    "name": "WebhookEvent",
    "purpose": "Provider event, signature status, idempotency and processing result",
    "priority": "Critical",
    "release": "MVP"
  },
  {
    "name": "SLARecord",
    "purpose": "Workflow or ticket SLA target, breach and escalation",
    "priority": "High",
    "release": "MVP"
  },
  {
    "name": "CustomerHealth",
    "purpose": "Adoption, billing, support, performance and risk score",
    "priority": "Medium",
    "release": "Growth"
  },
  {
    "name": "ProductDependency",
    "purpose": "Tool dependency, compatibility and configuration prerequisite",
    "priority": "High",
    "release": "MVP"
  },
  {
    "name": "PriceVersion",
    "purpose": "Versioned pricing and effective dates",
    "priority": "Critical",
    "release": "MVP"
  },
  {
    "name": "Coupon",
    "purpose": "Eligibility, value, limits and expiration",
    "priority": "Medium",
    "release": "MVP"
  }
];

export const decisions = [
  {
    "decision_id": "DEC-001",
    "decision": "Select canonical GitHub repository",
    "domain": "Architecture",
    "options": "XTREME-SYSTEMS/xtreme-ai-systems; Strategic-Minds/XTREME-AI-SYSTEMS; governed dual-repo model",
    "recommendation": "Unresolved",
    "priority": "Critical",
    "owner": "Operator",
    "required_by": "Before build docs",
    "status": "OPEN"
  },
  {
    "decision_id": "DEC-002",
    "decision": "Confirm canonical Base44 app",
    "domain": "Architecture",
    "options": "Xtreme AI Systems 6a69978f9454039c6021d362 or replacement",
    "recommendation": "Existing app appears strongest candidate",
    "priority": "Critical",
    "owner": "Operator",
    "required_by": "Before schema changes",
    "status": "OPEN"
  },
  {
    "decision_id": "DEC-003",
    "decision": "Record exact production domain",
    "domain": "Brand/Release",
    "options": "Exact purchased URL and DNS owner",
    "recommendation": "Unverified",
    "priority": "High",
    "owner": "Operator",
    "required_by": "Before environment plan",
    "status": "OPEN"
  },
  {
    "decision_id": "DEC-004",
    "decision": "Approve initial six products",
    "domain": "Product",
    "options": "Website; Brand; AI Receptionist; Missed-call/follow-up; Estimator/Proposal; Review Automation",
    "recommendation": "Recommended",
    "priority": "Critical",
    "owner": "Operator",
    "required_by": "Before pricing and build scope",
    "status": "OPEN"
  },
  {
    "decision_id": "DEC-005",
    "decision": "Select pricing architecture",
    "domain": "Finance",
    "options": "Product-based; tier-based; outcome-based",
    "recommendation": "Outcome bundles + individual add-ons recommended",
    "priority": "Critical",
    "owner": "Operator",
    "required_by": "Before checkout design",
    "status": "OPEN"
  },
  {
    "decision_id": "DEC-006",
    "decision": "Approve pilot cohort",
    "domain": "Release",
    "options": "5 PCU students; 5 XPS customers; 2 established; 1 commercial",
    "recommendation": "Proposed",
    "priority": "High",
    "owner": "Operator",
    "required_by": "Before pilot",
    "status": "OPEN"
  },
  {
    "decision_id": "DEC-007",
    "decision": "Select payment provider",
    "domain": "Commerce",
    "options": "Stripe; Square; hybrid",
    "recommendation": "Unresolved",
    "priority": "Critical",
    "owner": "Operator",
    "required_by": "Before checkout implementation",
    "status": "OPEN"
  },
  {
    "decision_id": "DEC-008",
    "decision": "Confirm Twilio account structure",
    "domain": "Communications",
    "options": "Master + subaccounts; direct customer accounts; hybrid",
    "recommendation": "Unresolved",
    "priority": "Critical",
    "owner": "Operator",
    "required_by": "Before communications build",
    "status": "OPEN"
  },
  {
    "decision_id": "DEC-009",
    "decision": "Select CRM architecture",
    "domain": "Sales",
    "options": "Native CRM; provider integration; hybrid",
    "recommendation": "Native core recommended",
    "priority": "High",
    "owner": "Operator",
    "required_by": "Before CRM docs",
    "status": "OPEN"
  },
  {
    "decision_id": "DEC-010",
    "decision": "Define support model",
    "domain": "Support",
    "options": "Self-service; managed; tiered",
    "recommendation": "Tiered recommended",
    "priority": "High",
    "owner": "Operator",
    "required_by": "Before pricing",
    "status": "OPEN"
  },
  {
    "decision_id": "DEC-011",
    "decision": "Define revision policy",
    "domain": "Fulfillment",
    "options": "Included revisions and paid additional changes",
    "recommendation": "Unresolved",
    "priority": "High",
    "owner": "Operator",
    "required_by": "Before customer terms",
    "status": "OPEN"
  },
  {
    "decision_id": "DEC-012",
    "decision": "Approve public PCU/XPS relationship language",
    "domain": "Brand/Legal",
    "options": "Official endorsement, customer benefit and eligibility language",
    "recommendation": "Unresolved",
    "priority": "Critical",
    "owner": "Operator/Leadership",
    "required_by": "Before public copy",
    "status": "OPEN"
  },
  {
    "decision_id": "DEC-013",
    "decision": "Select analytics provider",
    "domain": "Analytics",
    "options": "Vercel Analytics; PostHog; GA4; other",
    "recommendation": "Unresolved",
    "priority": "Medium",
    "owner": "Operator",
    "required_by": "Before event implementation",
    "status": "OPEN"
  },
  {
    "decision_id": "DEC-014",
    "decision": "Select e-sign provider",
    "domain": "Sales",
    "options": "Native acceptance; Dropbox Sign; DocuSign; other",
    "recommendation": "Unresolved",
    "priority": "Medium",
    "owner": "Operator",
    "required_by": "Before proposal implementation",
    "status": "OPEN"
  },
  {
    "decision_id": "DEC-015",
    "decision": "Select accounting integration",
    "domain": "Finance",
    "options": "QuickBooks; Xero; none at MVP",
    "recommendation": "Unresolved",
    "priority": "Medium",
    "owner": "Operator",
    "required_by": "Before advanced finance",
    "status": "OPEN"
  }
];

export const risks = [
  {
    "risk_id": "RISK-001",
    "risk": "Canonical repository is unresolved",
    "category": "Architecture",
    "likelihood": "High",
    "impact": "High",
    "severity": "Critical",
    "consequence": "Two Xtreme AI Systems repositories may drift or overwrite authority.",
    "mitigation": "Select canonical implementation and governance relationship.",
    "owner": "Operator",
    "status": "OPEN"
  },
  {
    "risk_id": "RISK-002",
    "risk": "Product catalog is too broad for first launch",
    "category": "Product",
    "likelihood": "High",
    "impact": "High",
    "severity": "High",
    "consequence": "Launching dozens of tools can confuse customers and overload fulfillment.",
    "mitigation": "Approve a six-product MVP and hide later tools behind roadmap/flags.",
    "owner": "Operator",
    "status": "OPEN"
  },
  {
    "risk_id": "RISK-003",
    "risk": "Pricing is planning-only",
    "category": "Finance",
    "likelihood": "High",
    "impact": "High",
    "severity": "High",
    "consequence": "Unverified pricing may create poor margins or customer confusion.",
    "mitigation": "Run unit economics, competitor research and pilot pricing.",
    "owner": "Finance",
    "status": "OPEN"
  },
  {
    "risk_id": "RISK-004",
    "risk": "Twilio reseller terms not verified",
    "category": "Compliance",
    "likelihood": "High",
    "impact": "High",
    "severity": "Critical",
    "consequence": "Markup, onboarding and responsibility model may differ from assumptions.",
    "mitigation": "Review current agreement and provider program terms.",
    "owner": "Operator/Legal",
    "status": "OPEN"
  },
  {
    "risk_id": "RISK-005",
    "risk": "Messaging consent failure",
    "category": "Compliance",
    "likelihood": "Medium",
    "impact": "High",
    "severity": "Critical",
    "consequence": "Improper SMS/voice/WhatsApp use can cause complaints and provider enforcement.",
    "mitigation": "Consent registry, templates, suppression and audit tests.",
    "owner": "Compliance",
    "status": "OPEN"
  },
  {
    "risk_id": "RISK-006",
    "risk": "AI makes unsupported technical claims",
    "category": "AI Safety",
    "likelihood": "Medium",
    "impact": "High",
    "severity": "Critical",
    "consequence": "Flooring advice or guarantees can create failures and liability.",
    "mitigation": "Approved knowledge, confidence labels and human technical review.",
    "owner": "Technical",
    "status": "OPEN"
  },
  {
    "risk_id": "RISK-007",
    "risk": "Generated imagery presented as completed work",
    "category": "Trust",
    "likelihood": "Medium",
    "impact": "High",
    "severity": "High",
    "consequence": "Customers could be misled and brand trust damaged.",
    "mitigation": "Disclosure labels and separate verified project library.",
    "owner": "Marketing",
    "status": "OPEN"
  },
  {
    "risk_id": "RISK-008",
    "risk": "Automations report false success",
    "category": "Governance",
    "likelihood": "Medium",
    "impact": "High",
    "severity": "Critical",
    "consequence": "Missing evidence could allow broken releases or messages.",
    "mitigation": "Fail-closed receipts and validator gates.",
    "owner": "Validator",
    "status": "OPEN"
  },
  {
    "risk_id": "RISK-009",
    "risk": "Tenant data exposure",
    "category": "Security",
    "likelihood": "Low",
    "impact": "Very High",
    "severity": "Critical",
    "consequence": "Weak RLS could expose customer leads, billing or messages.",
    "mitigation": "Account-scoped RLS, penetration tests and audit logs.",
    "owner": "Security",
    "status": "OPEN"
  },
  {
    "risk_id": "RISK-010",
    "risk": "Usage costs exceed revenue",
    "category": "Finance",
    "likelihood": "Medium",
    "impact": "High",
    "severity": "High",
    "consequence": "AI, voice, media and messaging costs may erode margin.",
    "mitigation": "Meter usage, budgets, included units and margin alerts.",
    "owner": "Finance",
    "status": "OPEN"
  },
  {
    "risk_id": "RISK-011",
    "risk": "Operator becomes fulfillment bottleneck",
    "category": "Operations",
    "likelihood": "High",
    "impact": "High",
    "severity": "High",
    "consequence": "Manual review across every project limits scale.",
    "mitigation": "Standardized templates, queues, SLAs and delegated validator roles.",
    "owner": "Operations",
    "status": "OPEN"
  },
  {
    "risk_id": "RISK-012",
    "risk": "Approval delays stall projects",
    "category": "Customer Success",
    "likelihood": "High",
    "impact": "Medium",
    "severity": "High",
    "consequence": "Customers may not review options promptly.",
    "mitigation": "Clear deadlines, reminders, expiration and support.",
    "owner": "Customer Success",
    "status": "OPEN"
  },
  {
    "risk_id": "RISK-013",
    "risk": "Integration outage disrupts customer tools",
    "category": "Reliability",
    "likelihood": "Medium",
    "impact": "High",
    "severity": "High",
    "consequence": "Provider failure affects calls, billing or generation.",
    "mitigation": "Health monitoring, retries, graceful degradation and fallback.",
    "owner": "Engineering",
    "status": "OPEN"
  },
  {
    "risk_id": "RISK-014",
    "risk": "Payment/refund disputes",
    "category": "Commerce",
    "likelihood": "Medium",
    "impact": "High",
    "severity": "High",
    "consequence": "Unclear setup, revisions or usage charges create disputes.",
    "mitigation": "Clear scope, receipts, cancellation/refund policy and usage visibility.",
    "owner": "Billing",
    "status": "OPEN"
  },
  {
    "risk_id": "RISK-015",
    "risk": "Scope creep during custom projects",
    "category": "Operations",
    "likelihood": "High",
    "impact": "High",
    "severity": "High",
    "consequence": "Unlimited revisions and custom work destroy margin.",
    "mitigation": "Package scope, revision allowances and change-order workflow.",
    "owner": "Operator",
    "status": "OPEN"
  }
];

export const systemMeta = {
  system: "Xtreme AI Systems",
  version: "1.0.0",
  phase: "PLAN",
  step: "SYSTEM ORGANIZATION",
  workbook: "XTREME_AI_SYSTEMS_MASTER_CONTROL_WORKBOOK_V1.xlsx",
  sheetCount: 40,
  formulaCount: 451,
  validationStatus: "PASS"
};
